<?php

namespace Database\Seeders;

use App\Models\Currency;
use App\Models\User;
use Illuminate\Database\Seeder;

class CurrencySeeder extends Seeder
{
    private const CURRENCIES = [
        ['code' => 'AED', 'name' => 'UAE Dirham', 'symbol' => 'د.إ', 'decimal_places' => 2],
        ['code' => 'AFN', 'name' => 'Afghani', 'symbol' => '؋', 'decimal_places' => 2],
        ['code' => 'ALL', 'name' => 'Lek', 'symbol' => 'L', 'decimal_places' => 2],
        ['code' => 'AMD', 'name' => 'Armenian Dram', 'symbol' => '֏', 'decimal_places' => 2],
        ['code' => 'AOA', 'name' => 'Kwanza', 'symbol' => 'Kz', 'decimal_places' => 2],
        ['code' => 'ARS', 'name' => 'Argentine Peso', 'symbol' => '$', 'decimal_places' => 2],
        ['code' => 'AUD', 'name' => 'Australian Dollar', 'symbol' => '$', 'decimal_places' => 2],
        ['code' => 'AWG', 'name' => 'Aruban Florin', 'symbol' => 'ƒ', 'decimal_places' => 2],
        ['code' => 'AZN', 'name' => 'Azerbaijan Manat', 'symbol' => '₼', 'decimal_places' => 2],
        ['code' => 'BAM', 'name' => 'Convertible Mark', 'symbol' => 'KM', 'decimal_places' => 2],
        ['code' => 'BBD', 'name' => 'Barbados Dollar', 'symbol' => '$', 'decimal_places' => 2],
        ['code' => 'BDT', 'name' => 'Taka', 'symbol' => '৳', 'decimal_places' => 2],
        ['code' => 'BGN', 'name' => 'Bulgarian Lev', 'symbol' => 'лв', 'decimal_places' => 2],
        ['code' => 'BHD', 'name' => 'Bahraini Dinar', 'symbol' => '.د.ب', 'decimal_places' => 3],
        ['code' => 'BIF', 'name' => 'Burundi Franc', 'symbol' => 'FBu', 'decimal_places' => 0],
        ['code' => 'BMD', 'name' => 'Bermudian Dollar', 'symbol' => '$', 'decimal_places' => 2],
        ['code' => 'BND', 'name' => 'Brunei Dollar', 'symbol' => '$', 'decimal_places' => 2],
        ['code' => 'BOB', 'name' => 'Boliviano', 'symbol' => 'Bs.', 'decimal_places' => 2],
        ['code' => 'BRL', 'name' => 'Brazilian Real', 'symbol' => 'R$', 'decimal_places' => 2],
        ['code' => 'BSD', 'name' => 'Bahamian Dollar', 'symbol' => '$', 'decimal_places' => 2],
        ['code' => 'BTN', 'name' => 'Ngultrum', 'symbol' => 'Nu.', 'decimal_places' => 2],
        ['code' => 'BWP', 'name' => 'Pula', 'symbol' => 'P', 'decimal_places' => 2],
        ['code' => 'BYN', 'name' => 'Belarusian Ruble', 'symbol' => 'Br', 'decimal_places' => 2],
        ['code' => 'BZD', 'name' => 'Belize Dollar', 'symbol' => 'BZ$', 'decimal_places' => 2],
        ['code' => 'CAD', 'name' => 'Canadian Dollar', 'symbol' => '$', 'decimal_places' => 2],
        ['code' => 'CDF', 'name' => 'Congolese Franc', 'symbol' => 'FC', 'decimal_places' => 2],
        ['code' => 'CHF', 'name' => 'Swiss Franc', 'symbol' => 'CHF', 'decimal_places' => 2],
        ['code' => 'CLP', 'name' => 'Chilean Peso', 'symbol' => '$', 'decimal_places' => 0],
        ['code' => 'CNY', 'name' => 'Yuan Renminbi', 'symbol' => '¥', 'decimal_places' => 2],
        ['code' => 'COP', 'name' => 'Colombian Peso', 'symbol' => '$', 'decimal_places' => 2],
        ['code' => 'CRC', 'name' => 'Costa Rican Colon', 'symbol' => '₡', 'decimal_places' => 2],
        ['code' => 'CUP', 'name' => 'Cuban Peso', 'symbol' => '₱', 'decimal_places' => 2],
        ['code' => 'CZK', 'name' => 'Czech Koruna', 'symbol' => 'Kč', 'decimal_places' => 2],
        ['code' => 'DJF', 'name' => 'Djibouti Franc', 'symbol' => 'Fdj', 'decimal_places' => 0],
        ['code' => 'DKK', 'name' => 'Danish Krone', 'symbol' => 'kr', 'decimal_places' => 2],
        ['code' => 'DOP', 'name' => 'Dominican Peso', 'symbol' => 'RD$', 'decimal_places' => 2],
        ['code' => 'DZD', 'name' => 'Algerian Dinar', 'symbol' => 'دج', 'decimal_places' => 2],
        ['code' => 'EGP', 'name' => 'Egyptian Pound', 'symbol' => 'E£', 'decimal_places' => 2],
        ['code' => 'ERN', 'name' => 'Nakfa', 'symbol' => 'Nfk', 'decimal_places' => 2],
        ['code' => 'ETB', 'name' => 'Ethiopian Birr', 'symbol' => 'Br', 'decimal_places' => 2],
        ['code' => 'EUR', 'name' => 'Euro', 'symbol' => '€', 'decimal_places' => 2],
        ['code' => 'FJD', 'name' => 'Fiji Dollar', 'symbol' => '$', 'decimal_places' => 2],
        ['code' => 'FKP', 'name' => 'Falkland Islands Pound', 'symbol' => '£', 'decimal_places' => 2],
        ['code' => 'GBP', 'name' => 'Pound Sterling', 'symbol' => '£', 'decimal_places' => 2],
        ['code' => 'GEL', 'name' => 'Lari', 'symbol' => '₾', 'decimal_places' => 2],
        ['code' => 'GHS', 'name' => 'Ghana Cedi', 'symbol' => '₵', 'decimal_places' => 2],
        ['code' => 'GIP', 'name' => 'Gibraltar Pound', 'symbol' => '£', 'decimal_places' => 2],
        ['code' => 'GMD', 'name' => 'Dalasi', 'symbol' => 'D', 'decimal_places' => 2],
        ['code' => 'GNF', 'name' => 'Guinea Franc', 'symbol' => 'FG', 'decimal_places' => 0],
        ['code' => 'GTQ', 'name' => 'Quetzal', 'symbol' => 'Q', 'decimal_places' => 2],
        ['code' => 'GYD', 'name' => 'Guyana Dollar', 'symbol' => '$', 'decimal_places' => 2],
        ['code' => 'HKD', 'name' => 'Hong Kong Dollar', 'symbol' => '$', 'decimal_places' => 2],
        ['code' => 'HNL', 'name' => 'Lempira', 'symbol' => 'L', 'decimal_places' => 2],
        ['code' => 'HTG', 'name' => 'Gourde', 'symbol' => 'G', 'decimal_places' => 2],
        ['code' => 'HUF', 'name' => 'Forint', 'symbol' => 'Ft', 'decimal_places' => 2],
        ['code' => 'IDR', 'name' => 'Rupiah', 'symbol' => 'Rp', 'decimal_places' => 2],
        ['code' => 'ILS', 'name' => 'New Israeli Sheqel', 'symbol' => '₪', 'decimal_places' => 2],
        ['code' => 'INR', 'name' => 'Indian Rupee', 'symbol' => '₹', 'decimal_places' => 2],
        ['code' => 'IQD', 'name' => 'Iraqi Dinar', 'symbol' => 'ع.د', 'decimal_places' => 3],
        ['code' => 'IRR', 'name' => 'Iranian Rial', 'symbol' => '﷼', 'decimal_places' => 2],
        ['code' => 'ISK', 'name' => 'Iceland Krona', 'symbol' => 'kr', 'decimal_places' => 0],
        ['code' => 'JMD', 'name' => 'Jamaican Dollar', 'symbol' => 'J$', 'decimal_places' => 2],
        ['code' => 'JOD', 'name' => 'Jordanian Dinar', 'symbol' => 'د.ا', 'decimal_places' => 3],
        ['code' => 'JPY', 'name' => 'Yen', 'symbol' => '¥', 'decimal_places' => 0],
        ['code' => 'KES', 'name' => 'Kenyan Shilling', 'symbol' => 'KSh', 'decimal_places' => 2],
        ['code' => 'KGS', 'name' => 'Som', 'symbol' => 'с', 'decimal_places' => 2],
        ['code' => 'KHR', 'name' => 'Riel', 'symbol' => '៛', 'decimal_places' => 2],
        ['code' => 'KMF', 'name' => 'Comoro Franc', 'symbol' => 'CF', 'decimal_places' => 0],
        ['code' => 'KRW', 'name' => 'Won', 'symbol' => '₩', 'decimal_places' => 0],
        ['code' => 'KWD', 'name' => 'Kuwaiti Dinar', 'symbol' => 'د.ك', 'decimal_places' => 3],
        ['code' => 'KZT', 'name' => 'Tenge', 'symbol' => '₸', 'decimal_places' => 2],
        ['code' => 'LAK', 'name' => 'Kip', 'symbol' => '₭', 'decimal_places' => 2],
        ['code' => 'LBP', 'name' => 'Lebanese Pound', 'symbol' => 'ل.ل', 'decimal_places' => 2],
        ['code' => 'LKR', 'name' => 'Sri Lanka Rupee', 'symbol' => 'Rs', 'decimal_places' => 2],
        ['code' => 'LRD', 'name' => 'Liberian Dollar', 'symbol' => '$', 'decimal_places' => 2],
        ['code' => 'LYD', 'name' => 'Libyan Dinar', 'symbol' => 'ل.د', 'decimal_places' => 3],
        ['code' => 'MAD', 'name' => 'Moroccan Dirham', 'symbol' => 'د.م.', 'decimal_places' => 2],
        ['code' => 'MGA', 'name' => 'Malagasy Ariary', 'symbol' => 'Ar', 'decimal_places' => 2],
        ['code' => 'MMK', 'name' => 'Kyat', 'symbol' => 'K', 'decimal_places' => 2],
        ['code' => 'MNT', 'name' => 'Tugrik', 'symbol' => '₮', 'decimal_places' => 2],
        ['code' => 'MOP', 'name' => 'Pataca', 'symbol' => 'MOP$', 'decimal_places' => 2],
        ['code' => 'MUR', 'name' => 'Mauritius Rupee', 'symbol' => '₨', 'decimal_places' => 2],
        ['code' => 'MVR', 'name' => 'Rufiyaa', 'symbol' => 'Rf', 'decimal_places' => 2],
        ['code' => 'MWK', 'name' => 'Kwacha', 'symbol' => 'MK', 'decimal_places' => 2],
        ['code' => 'MXN', 'name' => 'Mexican Peso', 'symbol' => '$', 'decimal_places' => 2],
        ['code' => 'MYR', 'name' => 'Malaysian Ringgit', 'symbol' => 'RM', 'decimal_places' => 2],
        ['code' => 'MZN', 'name' => 'Mozambique Metical', 'symbol' => 'MT', 'decimal_places' => 2],
        ['code' => 'NGN', 'name' => 'Naira', 'symbol' => '₦', 'decimal_places' => 2],
        ['code' => 'NOK', 'name' => 'Norwegian Krone', 'symbol' => 'kr', 'decimal_places' => 2],
        ['code' => 'NPR', 'name' => 'Nepalese Rupee', 'symbol' => 'रु', 'decimal_places' => 2],
        ['code' => 'NZD', 'name' => 'New Zealand Dollar', 'symbol' => '$', 'decimal_places' => 2],
        ['code' => 'OMR', 'name' => 'Rial Omani', 'symbol' => 'ر.ع.', 'decimal_places' => 3],
        ['code' => 'PEN', 'name' => 'Sol', 'symbol' => 'S/', 'decimal_places' => 2],
        ['code' => 'PHP', 'name' => 'Philippine Peso', 'symbol' => '₱', 'decimal_places' => 2],
        ['code' => 'PKR', 'name' => 'Pakistan Rupee', 'symbol' => '₨', 'decimal_places' => 2],
        ['code' => 'PLN', 'name' => 'Zloty', 'symbol' => 'zł', 'decimal_places' => 2],
        ['code' => 'QAR', 'name' => 'Qatari Rial', 'symbol' => 'ر.ق', 'decimal_places' => 2],
        ['code' => 'RON', 'name' => 'Romanian Leu', 'symbol' => 'lei', 'decimal_places' => 2],
        ['code' => 'RSD', 'name' => 'Serbian Dinar', 'symbol' => 'дин.', 'decimal_places' => 2],
        ['code' => 'RUB', 'name' => 'Russian Ruble', 'symbol' => '₽', 'decimal_places' => 2],
        ['code' => 'RWF', 'name' => 'Rwanda Franc', 'symbol' => 'FRw', 'decimal_places' => 0],
        ['code' => 'SAR', 'name' => 'Saudi Riyal', 'symbol' => '﷼', 'decimal_places' => 2],
        ['code' => 'SCR', 'name' => 'Seychelles Rupee', 'symbol' => '₨', 'decimal_places' => 2],
        ['code' => 'SEK', 'name' => 'Swedish Krona', 'symbol' => 'kr', 'decimal_places' => 2],
        ['code' => 'SGD', 'name' => 'Singapore Dollar', 'symbol' => '$', 'decimal_places' => 2],
        ['code' => 'THB', 'name' => 'Baht', 'symbol' => '฿', 'decimal_places' => 2],
        ['code' => 'TND', 'name' => 'Tunisian Dinar', 'symbol' => 'د.ت', 'decimal_places' => 3],
        ['code' => 'TRY', 'name' => 'Turkish Lira', 'symbol' => '₺', 'decimal_places' => 2],
        ['code' => 'TWD', 'name' => 'New Taiwan Dollar', 'symbol' => 'NT$', 'decimal_places' => 2],
        ['code' => 'UAH', 'name' => 'Hryvnia', 'symbol' => '₴', 'decimal_places' => 2],
        ['code' => 'UGX', 'name' => 'Uganda Shilling', 'symbol' => 'USh', 'decimal_places' => 0],
        ['code' => 'USD', 'name' => 'US Dollar', 'symbol' => '$', 'decimal_places' => 2],
        ['code' => 'UZS', 'name' => 'Uzbekistan Sum', 'symbol' => "so'm", 'decimal_places' => 2],
        ['code' => 'VND', 'name' => 'Dong', 'symbol' => '₫', 'decimal_places' => 0],
        ['code' => 'XAF', 'name' => 'CFA Franc BEAC', 'symbol' => 'FCFA', 'decimal_places' => 0],
        ['code' => 'XCD', 'name' => 'East Caribbean Dollar', 'symbol' => '$', 'decimal_places' => 2],
        ['code' => 'XOF', 'name' => 'CFA Franc BCEAO', 'symbol' => 'CFA', 'decimal_places' => 0],
        ['code' => 'XPF', 'name' => 'CFP Franc', 'symbol' => '₣', 'decimal_places' => 0],
        ['code' => 'YER', 'name' => 'Yemeni Rial', 'symbol' => '﷼', 'decimal_places' => 2],
        ['code' => 'ZAR', 'name' => 'Rand', 'symbol' => 'R', 'decimal_places' => 2],
        ['code' => 'ZMW', 'name' => 'Zambian Kwacha', 'symbol' => 'ZK', 'decimal_places' => 2],
    ];

    public function run(): void
    {
        $userId = User::query()
            ->where('email', 'main.branch@kiteledger.local')
            ->value('id');

        $userId ??= User::query()->value('id');

        foreach (self::CURRENCIES as $currency) {
            Currency::query()->updateOrCreate(
                ['code' => $currency['code']],
                [
                    'name' => $currency['name'],
                    'symbol' => $currency['symbol'],
                    'decimal_places' => $currency['decimal_places'],
                    'is_base' => $currency['code'] === 'USD',
                    'active' => true,
                    'user_add_id' => $userId,
                ]
            );
        }
    }
}