<?php

declare(strict_types=1);

namespace App\Services\Documents\Pipeline;

use App\Services\Documents\Contracts\ExtractedField;
use App\Services\Documents\Contracts\FieldValidationState;

/**
 * Application confidence, computed from evidence rather than taken on trust.
 *
 * A model's self-reported confidence is not calibrated: it is generated by the
 * same process that produced the value, so a confidently misread total arrives
 * with a high score attached. It is useful as one signal among several and
 * worthless as the only one.
 *
 * This combines it with things the application can actually verify — whether
 * the value was found in the document's own text, whether the page it came from
 * was digital or a scan, whether it survived arithmetic validation, and whether
 * it parsed into the type the field expects.
 */
final class FieldConfidenceCalculator
{
    /** Starting point when the model offered no opinion of its own. */
    private const NEUTRAL = 0.6;

    /**
     * Recomputes confidence for one field.
     *
     * @param  bool  $locatedInText  the value was found in the document's text layer
     * @param  PageKind|null  $sourcePageKind  how the page it came from was read
     */
    public function forField(
        ExtractedField $field,
        bool $locatedInText = false,
        ?PageKind $sourcePageKind = null,
    ): float {
        if (! $field->isPresent()) {
            return 0.0;
        }

        // A user-entered or user-confirmed value is not a guess.
        if ($field->validationState === FieldValidationState::UserConfirmed) {
            return 1.0;
        }

        $score = $field->confidence ?? self::NEUTRAL;

        // Verified provenance is the strongest signal available: the value was
        // found character-for-character in text the document itself carries.
        if ($locatedInText) {
            $score += 0.25;
        }

        $score += match ($sourcePageKind) {
            PageKind::NativeText => 0.05,
            // Vision transcription is where digits get misread, so a value from
            // a scan starts lower however sure the model sounds.
            PageKind::ScannedImage => -0.20,
            PageKind::Mixed => -0.10,
            PageKind::Unreadable => -0.30,
            default => 0.0,
        };

        // Arithmetic that does not reconcile outweighs any stated certainty.
        $score += match ($field->validationState) {
            FieldValidationState::Conflict => -0.45,
            FieldValidationState::LowConfidence => -0.15,
            FieldValidationState::Missing => -0.50,
            default => 0.0,
        };

        // A figure KiteLedger calculated is exactly as reliable as its inputs,
        // which the reviewer is already being shown; it is never presented as a
        // high-confidence reading of the page.
        if ($field->origin->value === 'derived') {
            $score = min($score, 0.65);
        }

        return round(max(0.0, min(1.0, $score)), 3);
    }

    /**
     * A label the review screen can show without exposing a raw percentage,
     * which invites false precision.
     */
    public function label(float $confidence): string
    {
        return match (true) {
            $confidence >= 0.85 => 'High',
            $confidence >= 0.60 => 'Medium',
            $confidence > 0.0 => 'Low',
            default => 'Not found',
        };
    }
}
