<?php
namespace App\Http\Controllers\Central;
use App\Http\Controllers\Controller;use App\Jobs\SaaS\DeliverCommunicationRecipientJob;use App\Models\Central\CommunicationCampaign;use App\Models\Central\CommunicationDelivery;use App\Models\Central\CommunicationRecipient;use App\Models\Central\CommunicationSuppression;use App\Models\Central\Tenant;use App\Services\SaaS\CentralAuditService;use App\Services\SaaS\PlatformSettingsService;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;use Illuminate\Validation\Rule;use Illuminate\Validation\ValidationException;use Inertia\Inertia;
class CommunicationController extends Controller
{
 public function index(Request $request){$section=$request->string('section','campaigns')->toString();return Inertia::render('Central/Communication/Index',['section'=>$section,'campaigns'=>CommunicationCampaign::withCount(['recipients','deliveries'])->latest()->paginate(25)->withQueryString(),'deliveries'=>CommunicationDelivery::with(['recipient:id,name,email,phone','campaign:id,name,channel'])->latest()->limit(100)->get(),'suppressions'=>CommunicationSuppression::latest('suppressed_at')->get(),'customers'=>Tenant::whereNotNull('owner_email')->orderBy('company_name')->get(['id','company_name','owner_name','owner_email','owner_phone'])]);}
 public function store(Request $request,CentralAuditService $audit){$data=$request->validate(['name'=>['required','string','max:255'],'channel'=>['required',Rule::in(['email','sms'])],'subject'=>['nullable','required_if:channel,email','string','max:255'],'content'=>['required','string','max:100000'],'scheduled_at'=>['nullable','date','after:now'],'customer_ids'=>['nullable','array'],'customer_ids.*'=>['string','exists:tenants,id'],'manual_recipients'=>['nullable','string','max:100000'],'consent_source'=>['required','string','max:255']]);$campaign=DB::connection(config('tenancy.database.central_connection'))->transaction(function()use($data,$request){$campaign=CommunicationCampaign::create(['name'=>$data['name'],'channel'=>$data['channel'],'subject'=>$data['subject']??null,'content'=>$data['content'],'status'=>'draft','scheduled_at'=>$data['scheduled_at']??null,'created_by'=>$request->user('central')->id]);$customers=Tenant::whereIn('id',$data['customer_ids']??[])->get();foreach($customers as $customer)$this->recipient($campaign,['tenant_id'=>$customer->id,'name'=>$customer->owner_name,'email'=>$customer->owner_email,'phone'=>$customer->owner_phone],$data['consent_source']);foreach(preg_split('/\r?\n/',trim((string)($data['manual_recipients']??'')), -1,PREG_SPLIT_NO_EMPTY) as $line){$parts=array_map('trim',str_getcsv($line));$destination=$parts[1]??$parts[0]??null;$this->recipient($campaign,['name'=>count($parts)>1?$parts[0]:null,'email'=>$data['channel']==='email'?$destination:null,'phone'=>$data['channel']==='sms'?$destination:null],$data['consent_source']);}return $campaign;});$audit->log($request,'communication.campaign_created',$campaign,[],['name'=>$campaign->name,'channel'=>$campaign->channel,'recipients'=>$campaign->recipients()->count()]);return back()->with('success','Campaign draft created.');}
 public function import(Request $request,CommunicationCampaign $campaign){$request->validate(['file'=>['required','file','mimes:csv,txt','max:5120'],'consent_source'=>['required','string','max:255']]);$handle=fopen($request->file('file')->getRealPath(),'r');$header=array_map(fn($v)=>strtolower(trim($v)),fgetcsv($handle)?:[]);$count=0;while(($row=fgetcsv($handle))!==false){$item=array_combine($header,array_pad($row,count($header),null));if(!$item)continue;$this->recipient($campaign,['name'=>$item['name']??null,'email'=>$item['email']??null,'phone'=>$item['phone']??null],$request->string('consent_source'));$count++;}fclose($handle);return back()->with('success',$count.' recipients imported.');}
 public function send(Request $request,CommunicationCampaign $campaign,CentralAuditService $audit,PlatformSettingsService $settings){abort_if(in_array($campaign->status,['sending','completed','cancelled'],true),409,'This campaign cannot be sent again.');abort_if(!$campaign->recipients()->exists(),422,'Add at least one consented recipient.');$queued=(bool)$settings->get('queue_scheduler.queue_enabled',true);$scheduled=$campaign->scheduled_at&&$campaign->scheduled_at->isFuture();if($scheduled&&!$queued)throw ValidationException::withMessages(['scheduled_at'=>'Enable queue processing before scheduling a campaign. Immediate campaigns can be sent while the queue is off.']);$campaign->update(['status'=>$scheduled?'scheduled':'sending','started_at'=>$scheduled?null:now()]);$campaign->recipients()->where('status','pending')->pluck('id')->each(function($id)use($campaign,$queued,$scheduled){$job=new DeliverCommunicationRecipientJob($id);if($queued){$job->onConnection('database')->onQueue('communication');$scheduled?dispatch($job->delay($campaign->scheduled_at)):dispatch($job);}else dispatch_sync($job);});$audit->log($request,'communication.campaign_sent',$campaign,[],['scheduled_at'=>$campaign->scheduled_at,'delivery_mode'=>$queued?'queue':'immediate']);return back()->with('success',$scheduled?'Campaign scheduled.':($queued?'Campaign queued for delivery.':'Campaign delivered immediately.'));}
 public function cancel(Request $request,CommunicationCampaign $campaign){abort_if($campaign->status==='completed',409);$campaign->update(['status'=>'cancelled']);$campaign->recipients()->where('status','pending')->update(['status'=>'cancelled']);return back()->with('success','Campaign cancelled.');}
 public function retry(Request $request,CommunicationCampaign $campaign,PlatformSettingsService $settings){$ids=$campaign->recipients()->where('status','failed')->pluck('id');$campaign->update(['status'=>'sending']);$queued=(bool)$settings->get('queue_scheduler.queue_enabled',true);$ids->each(function($id)use($queued){$job=new DeliverCommunicationRecipientJob($id);$queued?dispatch($job->onConnection('database')->onQueue('communication')):dispatch_sync($job);});return back()->with('success',$ids->count().($queued?' failed deliveries queued again.':' failed deliveries retried immediately.'));}
 public function suppress(Request $request){$data=$request->validate(['channel'=>['required',Rule::in(['email','sms'])],'destination'=>['required','string','max:255'],'reason'=>['nullable','string','max:500']]);CommunicationSuppression::updateOrCreate(['channel'=>$data['channel'],'destination'=>$data['destination']],$data+['suppressed_at'=>now()]);return back()->with('success','Recipient suppressed.');}
 public function unsuppress(CommunicationSuppression $suppression){$suppression->delete();return back()->with('success','Suppression removed.');}
 public function unsubscribe(string $token){$recipient=CommunicationRecipient::where('unsubscribe_token',$token)->firstOrFail();$destination=$recipient->email?:$recipient->phone;$channel=$recipient->email?'email':'sms';CommunicationSuppression::updateOrCreate(['channel'=>$channel,'destination'=>$destination],['reason'=>'Recipient unsubscribe','suppressed_at'=>now()]);$recipient->update(['status'=>'unsubscribed']);return response('<!doctype html><title>Unsubscribed</title><main style="font-family:sans-serif;max-width:600px;margin:80px auto"><h1>You are unsubscribed</h1><p>You will no longer receive marketing messages from us.</p></main>');}
 private function recipient(CommunicationCampaign $campaign,array $data,string $source):void{$destination=$campaign->channel==='email'?strtolower(trim((string)($data['email']??''))):preg_replace('/[^+0-9]/','',(string)($data['phone']??''));if(!$destination)return;CommunicationRecipient::firstOrCreate(['campaign_id'=>$campaign->id,'email'=>$campaign->channel==='email'?$destination:null,'phone'=>$campaign->channel==='sms'?$destination:null],$data+['consent_source'=>$source,'consented_at'=>now(),'status'=>'pending','unsubscribe_token'=>hash('sha256',Str::uuid().$destination)]);}
}
