import CentralLayout from '@/Layouts/CentralLayout';
import PageHeader from '@/Components/Central/PageHeader';
import RichTextEditor from '@/Components/Central/RichTextEditor';
import SectionCard from '@/Components/Central/SectionCard';
import StatusBadge from '@/Components/Central/StatusBadge';
import { formatDate, formatMoney } from '@/Components/Central/formatters';
import { DeleteOutlined, PaperClipOutlined } from '@ant-design/icons';
import { router } from '@inertiajs/react';
import { Alert, Button, Col, Form, Modal, Row, Select, Space, Switch, Tag, Timeline, Typography, Upload } from 'antd';

export default function SupportShow({ ticket, categories, admins, savedReplies, canDelete }) {
    const [form] = Form.useForm();
    const update = (changes) => router.patch(route('central.support.tickets.update', ticket.id), changes, { preserveScroll: true });
    const reply = (values) => router.post(route('central.support.tickets.reply', ticket.id), { ...values, attachments: values.attachments?.map((item) => item.originFileObj) }, { forceFormData: true, preserveScroll: true, onSuccess: () => form.resetFields() });
    return <CentralLayout title={ticket.ticket_number}>
        <PageHeader eyebrow="Support Ticket" title={`${ticket.ticket_number} · ${ticket.subject}`} description={`${ticket.requester_name} · ${ticket.requester_email}`} actions={<Space><StatusBadge value={ticket.priority}/><StatusBadge value={ticket.status}/>{canDelete && <Button danger icon={<DeleteOutlined/>} onClick={() => Modal.confirm({ title: 'Delete support ticket?', content: 'The ticket will be soft deleted and removed from the active inbox.', okText: 'Delete ticket', okButtonProps: { danger: true }, onOk: () => router.delete(route('central.support.tickets.destroy', ticket.id)) })}>Delete</Button>}</Space>}/>
        <Row gutter={[18, 18]}>
            <Col xs={24} xl={16}><SectionCard title="Conversation"><Alert type="info" showIcon message={ticket.description} style={{ marginBottom: 18 }}/>{ticket.messages.map((message) => <div key={message.id} style={{ padding: 16, marginBottom: 12, border: `1px solid ${message.is_internal_note ? '#f59e0b' : '#e5e7eb'}`, background: message.is_internal_note ? '#fffbeb' : '#fff', borderRadius: 12 }}><Space><Typography.Text strong>{message.sender_name}</Typography.Text><Tag>{message.sender_type}</Tag>{message.is_internal_note && <Tag color="orange">Internal note</Tag>}<Typography.Text type="secondary">{formatDate(message.created_at, true)}</Typography.Text></Space><div style={{ marginTop: 10 }} dangerouslySetInnerHTML={{ __html: message.html_body || message.plain_body }}/>{message.attachments?.map((file) => <Button key={file.id} type="link" icon={<PaperClipOutlined/>} href={route('central.support.attachments.download', file.id)}>{file.original_filename}</Button>)}</div>)}<Form form={form} layout="vertical" onFinish={reply}><Form.Item name="body" label="Reply" rules={[{ required: true }]}><RichTextEditor autosaveKey={`admin.ticket.${ticket.id}`}/></Form.Item><Form.Item name="saved" label="Saved reply"><Select allowClear placeholder="Insert saved reply" options={savedReplies.map((item) => ({ value: item.id, label: item.title }))} onChange={(id) => form.setFieldValue('body', savedReplies.find((item) => item.id === id)?.body || '')}/></Form.Item><Form.Item name="attachments" valuePropName="fileList" getValueFromEvent={(event) => event.fileList}><Upload beforeUpload={() => false} multiple maxCount={5}><Button icon={<PaperClipOutlined/>}>Attach files</Button></Upload></Form.Item><Form.Item name="is_internal_note" valuePropName="checked"><Switch/> <span style={{ marginLeft: 8 }}>Internal note (never visible to tenant)</span></Form.Item><Button type="primary" htmlType="submit">Send reply</Button></Form></SectionCard></Col>
            <Col xs={24} xl={8}><SectionCard title="Ticket controls"><Form layout="vertical"><Form.Item label="Status"><Select value={ticket.status} onChange={(status) => update({ status })} options={['open', 'pending_support', 'pending_customer', 'resolved', 'closed'].map((value) => ({ value, label: value.replaceAll('_', ' ') }))}/></Form.Item><Form.Item label="Priority"><Select value={ticket.priority} onChange={(priority) => update({ priority })} options={['low', 'normal', 'high', 'urgent'].map((value) => ({ value, label: value }))}/></Form.Item><Form.Item label="Category"><Select value={ticket.category_id} onChange={(category_id) => update({ category_id })} options={categories.map((item) => ({ value: item.id, label: item.name }))}/></Form.Item><Form.Item label="Assignee"><Select allowClear value={ticket.assigned_admin_id} onChange={(assigned_admin_id) => update({ assigned_admin_id })} options={admins.map((item) => ({ value: item.id, label: item.name }))}/></Form.Item></Form><div className="central-data-grid" style={{ gridTemplateColumns: '1fr' }}><Data label="First response due" value={formatDate(ticket.first_response_due_at, true)}/><Data label="Resolution due" value={formatDate(ticket.resolution_due_at, true)}/><Data label="SLA" value={ticket.sla_breached_at ? <StatusBadge value="breached"/> : <StatusBadge value="healthy"/>}/><Data label="Tenant" value={ticket.tenant?.company_name}/><Data label="Plan" value={ticket.tenant?.subscription?.plan?.name}/></div></SectionCard><SectionCard title="Recent billing context" style={{ marginTop: 18 }}>{ticket.tenant?.invoices?.map((invoice) => <div className="central-attention" key={invoice.id}><span className="central-attention__copy"><strong>{invoice.invoice_number}</strong><span>{formatMoney(invoice.balance || invoice.total, invoice.currency)} · {invoice.status}</span></span></div>)}</SectionCard><SectionCard title="Audit timeline" style={{ marginTop: 18 }}><Timeline items={ticket.events.map((event) => ({ children: <><Typography.Text strong>{event.event.replaceAll('_', ' ')}</Typography.Text><br/><Typography.Text type="secondary">{formatDate(event.created_at, true)}</Typography.Text></> }))}/></SectionCard></Col>
        </Row>
    </CentralLayout>;
}

function Data({ label, value }) { return <div className="central-data-item"><span className="central-data-item__label">{label}</span><span>{value || '—'}</span></div>; }
