import CentralLayout from '@/Layouts/CentralLayout';
import PageHeader from '@/Components/Central/PageHeader';
import SectionCard from '@/Components/Central/SectionCard';
import { humanize } from '@/Components/Central/formatters';
import { useForm } from '@inertiajs/react';
import { Button, Checkbox, Col, Form, Input, InputNumber, Row, Select, Space } from 'antd';

const limits = ['max_users','max_branches','max_products','max_customers','max_invoices_per_month','max_storage_mb','max_ai_requests_per_month','max_api_requests_per_month','max_custom_domains','max_warehouses'];
const capabilities = ['allow_pos','allow_inventory','allow_hrm','allow_crm','allow_warehouse','allow_ai','allow_custom_domain','allow_multi_branch','allow_api_access'];

export default function PlanForm({ plan }) {
    const editing = Boolean(plan);
    const initial = {name:'',slug:'',description:'',price_monthly:0,price_yearly:0,currency:'USD',trial_days:14,sort_order:0,is_active:true,is_featured:false,...Object.fromEntries(limits.map((key)=>[key,null])),...Object.fromEntries(capabilities.map((key)=>[key,false])),...plan};
    const form = useForm(initial);
    const submit = () => editing ? form.put(route('central.plans.update',plan.id)) : form.post(route('central.plans.store'));
    const field = (name,label,node) => <Form.Item label={label} required={['name','slug','price_monthly','price_yearly','currency','trial_days'].includes(name)} validateStatus={form.errors[name]?'error':''} help={form.errors[name]}>{node || <Input value={form.data[name]} onChange={(event)=>form.setData(name,event.target.value)}/>}</Form.Item>;

    return <CentralLayout title={editing?'Edit plan':'Create plan'} breadcrumbs={[{title:'Plans & pricing'}]}><PageHeader eyebrow="Revenue configuration" title={editing?`Edit ${plan.name}`:'Create a plan'} description="Set pricing, workspace limits, and product capabilities. Changes apply to tenants assigned to this plan."/>
        <Form layout="vertical" onFinish={submit}><Row gutter={[16,16]}><Col xs={24} xl={15}>
            <SectionCard title="Plan identity" description="Customer-facing plan name and description."><Row gutter={16}><Col xs={24} md={12}>{field('name','Plan name')}</Col><Col xs={24} md={12}>{field('slug','Slug')}</Col><Col xs={24}>{field('description','Description',<Input.TextArea rows={4} value={form.data.description} onChange={(event)=>form.setData('description',event.target.value)}/>)}</Col></Row></SectionCard>
            <SectionCard title="Usage limits" description="Leave any value blank for unlimited usage." style={{marginTop:16}}><Row gutter={16}>{limits.map((key)=><Col xs={24} sm={12} md={8} key={key}>{field(key,humanize(key.replace('max_','')),<InputNumber min={0} placeholder="Unlimited" style={{width:'100%'}} value={form.data[key]} onChange={(value)=>form.setData(key,value)}/>)}</Col>)}</Row></SectionCard>
            <SectionCard title="Product capabilities" description="Choose the modules included in this plan." style={{marginTop:16}}><Row gutter={[12,16]}>{capabilities.map((key)=><Col xs={24} sm={12} md={8} key={key}><Checkbox checked={Boolean(form.data[key])} onChange={(event)=>form.setData(key,event.target.checked)}>{humanize(key.replace('allow_',''))}</Checkbox></Col>)}</Row></SectionCard>
        </Col><Col xs={24} xl={9}><SectionCard title="Pricing & availability" description="Billing cadence, trial window, and catalog visibility.">{field('currency','Currency',<Select value={form.data.currency} onChange={(value)=>form.setData('currency',value)} options={['USD','EUR','GBP','NPR','INR','AED'].map((value)=>({value,label:value}))}/>) }<Row gutter={12}><Col xs={12}>{field('price_monthly','Monthly price',<InputNumber min={0} precision={2} style={{width:'100%'}} value={form.data.price_monthly} onChange={(value)=>form.setData('price_monthly',value)}/>)}</Col><Col xs={12}>{field('price_yearly','Yearly price',<InputNumber min={0} precision={2} style={{width:'100%'}} value={form.data.price_yearly} onChange={(value)=>form.setData('price_yearly',value)}/>)}</Col><Col xs={12}>{field('trial_days','Trial days',<InputNumber min={0} max={365} style={{width:'100%'}} value={form.data.trial_days} onChange={(value)=>form.setData('trial_days',value)}/>)}</Col><Col xs={12}>{field('sort_order','Sort order',<InputNumber min={0} style={{width:'100%'}} value={form.data.sort_order} onChange={(value)=>form.setData('sort_order',value)}/>)}</Col></Row><Space direction="vertical"><Checkbox checked={Boolean(form.data.is_active)} onChange={(event)=>form.setData('is_active',event.target.checked)}>Active and assignable</Checkbox><Checkbox checked={Boolean(form.data.is_featured)} onChange={(event)=>form.setData('is_featured',event.target.checked)}>Feature as recommended</Checkbox></Space></SectionCard><div style={{marginTop:16,display:'flex',justifyContent:'flex-end',gap:8}}><Button onClick={()=>window.history.back()}>Cancel</Button><Button type="primary" htmlType="submit" loading={form.processing}>Save plan</Button></div></Col></Row></Form>
    </CentralLayout>;
}
