import CentralLayout from '@/Layouts/CentralLayout';
import PageHeader from '@/Components/Central/PageHeader';
import RichTextEditor from '@/Components/Central/RichTextEditor';
import SectionCard from '@/Components/Central/SectionCard';
import { formatDate } from '@/Components/Central/formatters';
import { EyeOutlined, HistoryOutlined, SaveOutlined } from '@ant-design/icons';
import { router } from '@inertiajs/react';
import { Alert, Button, Col, Collapse, DatePicker, Form, Input, InputNumber, Modal, Row, Select, Space, Switch, Tabs, Tag, Typography } from 'antd';
import dayjs from 'dayjs';

export default function PageEditor({ page, parents, media, revisions = [] }) {
    const editing = Boolean(page.id);
    const [form] = Form.useForm();
    const initial = { ...page, schema_json: page.schema_json ? JSON.stringify(page.schema_json, null, 2) : '', published_at: page.published_at ? dayjs(page.published_at) : null, scheduled_at: page.scheduled_at ? dayjs(page.scheduled_at) : null };
    const save = (values) => {
        const payload = { ...values, published_at: values.published_at?.toISOString() || null, scheduled_at: values.scheduled_at?.toISOString() || null };
        const options = { preserveScroll: true };
        editing ? router.put(route('central.website-pages.update', page.id), payload, options) : router.post(route('central.website-pages.store'), payload, options);
    };
    const restore = (revision) => Modal.confirm({ title: `Restore revision from ${formatDate(revision.created_at, true)}?`, content: 'The current version is saved as a revision before restoration.', okText: 'Restore revision', onOk: () => router.post(route('central.website-pages.revisions.restore', { page: page.id, revision: revision.id })) });
    const mediaOptions = media.map((item) => ({ value: item.id, label: item.title || item.original_filename }));
    const fields = [
        { key: 'content', label: 'Content', children: <ContentTab mediaOptions={mediaOptions}/> },
        { key: 'publishing', label: 'Publishing', children: <PublishingTab parents={parents}/> },
        { key: 'seo', label: 'SEO and sharing', children: <SeoTab/> },
        { key: 'revisions', label: <span><HistoryOutlined/> Revisions <Tag>{revisions.length}</Tag></span>, disabled: !editing, children: <RevisionTab revisions={revisions} restore={restore}/> },
    ];
    return <CentralLayout title={editing ? `Edit ${page.title}` : 'Create page'}>
        <PageHeader eyebrow="Website Pages" title={editing ? page.title : 'Create page'} description="Rich content, publication workflow, social metadata, schema, sitemap controls, and immutable revision history." actions={<Space>{editing && <Button icon={<EyeOutlined/>} onClick={() => window.open(route('central.website-pages.preview', page.id), '_blank', 'noopener,noreferrer')}>Preview</Button>}<Button type="primary" icon={<SaveOutlined/>} onClick={() => form.submit()}>Save page</Button></Space>}/>
        <Form form={form} layout="vertical" initialValues={initial} onFinish={save}><SectionCard><Tabs items={fields}/></SectionCard></Form>
    </CentralLayout>;
}

function ContentTab({ mediaOptions }) { return <Row gutter={[18, 18]}><Col xs={24} lg={16}><Form.Item name="title" label="Title" rules={[{ required: true }]}><Input size="large"/></Form.Item><Form.Item name="excerpt" label="Excerpt"><Input.TextArea rows={3} maxLength={2000} showCount/></Form.Item><Form.Item name="body" label="Rich content"><RichTextEditor/></Form.Item></Col><Col xs={24} lg={8}><Form.Item name="slug" label="Slug" rules={[{ required: true }, { pattern: /^[a-z0-9]+(?:-[a-z0-9]+)*$/, message: 'Use lowercase words separated by hyphens.' }]}><Input addonBefore="/"/></Form.Item><Form.Item name="page_type" label="Page type" rules={[{ required: true }]}><Input/></Form.Item><Form.Item name="layout" label="Layout" rules={[{ required: true }]}><Select options={['default', 'landing', 'legal', 'support', 'full_width'].map((value) => ({ value, label: value.replaceAll('_', ' ') }))}/></Form.Item><Form.Item name="featured_media_id" label="Featured image"><Select allowClear showSearch optionFilterProp="label" options={mediaOptions}/></Form.Item><Form.Item name="sort_order" label="Sort order"><InputNumber min={0} style={{ width: '100%' }}/></Form.Item></Col></Row>; }

function PublishingTab({ parents }) { return <Row gutter={[18, 18]}><Col xs={24} md={12}><Form.Item name="status" label="Status" rules={[{ required: true }]}><Select options={['draft', 'scheduled', 'published', 'archived'].map((value) => ({ value, label: value }))}/></Form.Item><Form.Item noStyle shouldUpdate={(previous, current) => previous.status !== current.status}>{({ getFieldValue }) => getFieldValue('status') === 'scheduled' && <Form.Item name="scheduled_at" label="Scheduled publication" rules={[{ required: true }]}><DatePicker showTime style={{ width: '100%' }}/></Form.Item>}</Form.Item><Form.Item name="published_at" label="Published date"><DatePicker showTime style={{ width: '100%' }}/></Form.Item></Col><Col xs={24} md={12}><Form.Item name="visibility" label="Visibility" rules={[{ required: true }]}><Select options={[{ value: 'public', label: 'Public' }, { value: 'private', label: 'Private' }]}/></Form.Item><Form.Item name="parent_id" label="Parent page"><Select allowClear showSearch optionFilterProp="label" options={parents.map((item) => ({ value: item.id, label: item.title }))}/></Form.Item></Col></Row>; }

function SeoTab() { return <><Row gutter={[18, 18]}><Col xs={24} md={12}><Form.Item name="meta_title" label="SEO title"><Input maxLength={255} showCount/></Form.Item><Form.Item name="meta_description" label="Meta description"><Input.TextArea rows={3} maxLength={500} showCount/></Form.Item><Form.Item name="focus_keyword" label="Focus keyword"><Input/></Form.Item><Form.Item name="canonical_url" label="Canonical URL"><Input type="url"/></Form.Item><Space size="large"><Form.Item name="robots_index" label="Index" valuePropName="checked"><Switch/></Form.Item><Form.Item name="robots_follow" label="Follow" valuePropName="checked"><Switch/></Form.Item></Space></Col><Col xs={24} md={12}><Form.Item name="og_title" label="Open Graph title"><Input/></Form.Item><Form.Item name="og_description" label="Open Graph description"><Input.TextArea rows={3}/></Form.Item><Form.Item name="og_image" label="Open Graph image URL"><Input/></Form.Item><Form.Item name="twitter_title" label="X/Twitter title"><Input/></Form.Item><Form.Item name="twitter_description" label="X/Twitter description"><Input.TextArea rows={2}/></Form.Item><Form.Item name="twitter_image" label="X/Twitter image URL"><Input/></Form.Item></Col></Row><Collapse items={[{ key: 'advanced', label: 'Structured data and sitemap', children: <Row gutter={[18, 18]}><Col xs={24} md={14}><Form.Item name="schema_json" label="Schema JSON" rules={[{ validator: (_, value) => { if (!value) return Promise.resolve(); try { JSON.parse(value); return Promise.resolve(); } catch { return Promise.reject(new Error('Enter valid JSON.')); } } }]}><Input.TextArea rows={12} className="central-code"/></Form.Item></Col><Col xs={24} md={10}><Form.Item name="sitemap_include" label="Include in sitemap" valuePropName="checked"><Switch/></Form.Item><Form.Item name="sitemap_priority" label="Priority"><InputNumber min={0} max={1} step={0.1} style={{ width: '100%' }}/></Form.Item><Form.Item name="sitemap_change_frequency" label="Change frequency"><Select options={['always', 'hourly', 'daily', 'weekly', 'monthly', 'yearly', 'never'].map((value) => ({ value, label: value }))}/></Form.Item></Col></Row> }]}/></>; }

function RevisionTab({ revisions, restore }) { if (!revisions.length) return <Alert type="info" showIcon message="A revision is stored before every update."/>; return <Space direction="vertical" style={{ width: '100%' }}>{revisions.map((revision) => <div key={revision.id} className="central-attention"><span className="central-attention__copy"><Typography.Text strong>{formatDate(revision.created_at, true)}</Typography.Text><Typography.Text type="secondary">Administrator #{revision.admin_id || 'system'}</Typography.Text></span><Button onClick={() => restore(revision)}>Restore</Button></div>)}</Space>; }
