<?php

namespace App\Services\AI\Tools\Queries;

use App\Services\AI\Tools\AiToolResult;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class JournalVoucherQueryTool extends BaseQueryTool
{
    public function cashBalance(Request $request): array
    {
        return $this->accountBalance($request, 'journal_voucher.cash_balance', 'Cash balance', ['cash']);
    }

    public function bankBalance(Request $request): array
    {
        return $this->accountBalance($request, 'journal_voucher.bank_balance', 'Bank balance', ['bank']);
    }

    public function highestDebitMovement(Request $request): array
    {
        return $this->accountMovement($request, 'journal_voucher.highest_debit_movement', 'Account with highest debit movement', 'debit_total');
    }

    public function highestCreditMovement(Request $request): array
    {
        return $this->accountMovement($request, 'journal_voucher.highest_credit_movement', 'Account with highest credit movement', 'credit_total');
    }

    public function highestExpenseThisMonth(Request $request): array
    {
        return $this->accountMovement($request, 'journal_voucher.highest_expense_this_month', 'Highest expense account this month', 'debit_total', ['expense'], true);
    }

    public function highestIncomeThisMonth(Request $request): array
    {
        return $this->accountMovement($request, 'journal_voucher.highest_income_this_month', 'Highest income account this month', 'credit_total', ['income', 'revenue'], true);
    }

    public function sourceForVoucher(Request $request): array
    {
        $this->authorize($request);
        $id = $request->input('voucher_id') ?: $request->input('id');
        if (!$id || !$this->tableExists(['journal_vouchers'])) {
            return $this->empty('journal_voucher.source', 'Journal voucher source', $request);
        }

        $query = DB::table('journal_vouchers')->where('journal_vouchers.id', $id);
        $this->applyBranch($query, $request, 'journal_vouchers');
        $record = $query->first(['id', 'voucher_no', 'source_type', 'source_id', 'source_no', 'source_module']);

        if (!$record) {
            return $this->empty('journal_voucher.source', 'Journal voucher source', $request);
        }

        $row = [
            'id' => (string) $record->id,
            'voucher_no' => $record->voucher_no,
            'source_type' => $record->source_type ?? null,
            'source_id' => $record->source_id ?? null,
            'source_no' => $record->source_no ?? null,
            'source_module' => $record->source_module ?? null,
            'open_url' => '/accounting/journal-vouchers/' . $record->id,
        ];

        return AiToolResult::query('journal_voucher.source', 'Journal voucher source', [$row], $this->contextFilters($request), 'The journal voucher source is shown from the database record.', $row['open_url'])->toArray();
    }

    public function autoGeneratedThisMonth(Request $request): array
    {
        $this->authorize($request);
        if (!$this->tableExists(['journal_vouchers'])) {
            return $this->empty('journal_voucher.auto_generated_this_month', 'Auto-generated JVs this month', $request);
        }

        $query = DB::table('journal_vouchers')->whereBetween('voucher_date', [now()->startOfMonth()->toDateString(), now()->endOfMonth()->toDateString()]);
        if (Schema::hasColumn('journal_vouchers', 'is_auto_generated')) {
            $query->where('is_auto_generated', true);
        } elseif (Schema::hasColumn('journal_vouchers', 'is_system_generated')) {
            $query->where('is_system_generated', true);
        }

        $this->applyApprovedFinancialTruth($query, 'journal_vouchers');
        $this->applyBranch($query, $request, 'journal_vouchers');

        $count = $query->count();
        $row = ['count' => $count, 'from_date' => now()->startOfMonth()->toDateString(), 'to_date' => now()->endOfMonth()->toDateString()];

        return AiToolResult::query('journal_voucher.auto_generated_this_month', 'Auto-generated JVs this month', [$row], $this->contextFilters($request), $count . ' auto-generated approved journal vouchers were created this month.', '/accounting/journal-vouchers')->toArray();
    }

    public function unbalanced(Request $request): array
    {
        $this->authorize($request);
        if (!$this->tableExists(['journal_vouchers', 'journal_voucher_lines'])) {
            return $this->empty('journal_voucher.unbalanced', 'Unbalanced journal vouchers', $request);
        }

        $query = DB::table('journal_vouchers')
            ->join('journal_voucher_lines', 'journal_vouchers.id', '=', 'journal_voucher_lines.journal_voucher_id')
            ->select([
                'journal_vouchers.id',
                'journal_vouchers.voucher_no',
                DB::raw('SUM(journal_voucher_lines.debit) as debit_total'),
                DB::raw('SUM(journal_voucher_lines.credit) as credit_total'),
            ])
            ->groupBy('journal_vouchers.id', 'journal_vouchers.voucher_no')
            ->havingRaw('ABS(SUM(journal_voucher_lines.debit) - SUM(journal_voucher_lines.credit)) > 0.01');

        $this->applyBranch($query, $request, 'journal_vouchers');
        $this->applyFiscalYear($query, $request, 'journal_vouchers', 'voucher_date');

        $records = $query->limit(20)->get()->map(fn ($row) => [
            'id' => (string) $row->id,
            'voucher_no' => $row->voucher_no,
            'debit_total' => $this->number($row->debit_total),
            'credit_total' => $this->number($row->credit_total),
            'difference' => $this->number(((float) $row->debit_total) - ((float) $row->credit_total)),
            'open_url' => '/accounting/journal-vouchers/' . $row->id,
        ])->all();

        return AiToolResult::query('journal_voucher.unbalanced', 'Unbalanced journal vouchers', $records, $this->contextFilters($request), count($records) ? count($records) . ' unbalanced journal vouchers were found.' : 'No unbalanced journal vouchers were found.', '/accounting/journal-vouchers')->toArray();
    }

    public function sourceModulesMostJvs(Request $request): array
    {
        $this->authorize($request);
        if (!$this->tableExists(['journal_vouchers'])) {
            return $this->empty('journal_voucher.source_modules_most_jvs', 'Source modules generating most JVs', $request);
        }

        $query = DB::table('journal_vouchers')
            ->select(['source_module', DB::raw('COUNT(*) as voucher_count'), DB::raw('SUM(total) as total')])
            ->groupBy('source_module');

        $this->applyApprovedFinancialTruth($query, 'journal_vouchers');
        $this->applyBranch($query, $request, 'journal_vouchers');
        $this->applyFiscalYear($query, $request, 'journal_vouchers', 'voucher_date');

        $records = $query->orderByDesc('voucher_count')->limit(10)->get()->map(fn ($row) => [
            'source_module' => $row->source_module ?: 'unknown',
            'voucher_count' => (int) $row->voucher_count,
            'total' => $this->number($row->total),
            'open_url' => '/accounting/journal-vouchers',
        ])->all();

        return AiToolResult::query('journal_voucher.source_modules_most_jvs', 'Source modules generating most JVs', $records, $this->contextFilters($request), count($records) ? ($records[0]['source_module'] . ' generated the most approved JVs with ' . $records[0]['voucher_count'] . ' vouchers.') : 'No source module JV data was found.', '/accounting/journal-vouchers')->toArray();
    }

    public function abnormalMovement(Request $request): array
    {
        return $this->accountMovement($request, 'journal_voucher.abnormal_movement', 'Accounts with abnormal movement', 'movement_abs');
    }

    private function accountBalance(Request $request, string $tool, string $title, array $needles): array
    {
        $this->authorize($request);

        if (!$this->tableExists(['journal_vouchers', 'journal_voucher_lines', 'accounts'])) {
            return $this->empty($tool, $title, $request);
        }

        $query = DB::table('journal_voucher_lines')
            ->join('journal_vouchers', 'journal_vouchers.id', '=', 'journal_voucher_lines.journal_voucher_id')
            ->join('accounts', 'accounts.id', '=', 'journal_voucher_lines.account_id')
            ->select([
                'accounts.id',
                'accounts.name',
                'accounts.code',
                DB::raw('SUM(journal_voucher_lines.debit) as debit_total'),
                DB::raw('SUM(journal_voucher_lines.credit) as credit_total'),
                DB::raw('SUM(journal_voucher_lines.debit) - SUM(journal_voucher_lines.credit) as balance'),
            ])
            ->groupBy('accounts.id', 'accounts.name', 'accounts.code');

        $query->where(function ($q) use ($needles) {
            foreach ($needles as $needle) {
                $q->orWhere('accounts.name', 'like', '%' . $needle . '%')
                    ->orWhere('accounts.code', 'like', '%' . $needle . '%');
            }
        });

        $this->applyApprovedFinancialTruth($query, 'journal_vouchers');
        $this->applyBranch($query, $request, 'journal_vouchers');
        $this->applyFiscalYear($query, $request, 'journal_vouchers', 'voucher_date');

        $records = $query->orderByDesc('balance')->limit(10)->get()->map(fn ($row) => [
            'account_id' => (string) $row->id,
            'account_name' => $row->name,
            'account_code' => $row->code,
            'debit_total' => $this->number($row->debit_total),
            'credit_total' => $this->number($row->credit_total),
            'balance' => $this->number($row->balance),
            'open_url' => '/accounting/accounts/' . $row->id,
        ])->all();

        $total = array_sum(array_column($records, 'balance'));
        return AiToolResult::query($tool, $title, $records, array_merge($this->contextFilters($request), ['approved' => true, 'void' => false]), $title . ' is ' . number_format($total, 2) . ' based on approved non-void journal vouchers.', '/accounting/accounts')->toArray();
    }

    private function accountMovement(Request $request, string $tool, string $title, string $sortColumn, array $natureNeedles = [], bool $thisMonth = false): array
    {
        $this->authorize($request);

        if (!$this->tableExists(['journal_vouchers', 'journal_voucher_lines', 'accounts'])) {
            return $this->empty($tool, $title, $request);
        }

        $query = DB::table('journal_voucher_lines')
            ->join('journal_vouchers', 'journal_vouchers.id', '=', 'journal_voucher_lines.journal_voucher_id')
            ->join('accounts', 'accounts.id', '=', 'journal_voucher_lines.account_id')
            ->select([
                'accounts.id',
                'accounts.name',
                'accounts.code',
                'accounts.nature',
                DB::raw('SUM(journal_voucher_lines.debit) as debit_total'),
                DB::raw('SUM(journal_voucher_lines.credit) as credit_total'),
                DB::raw('ABS(SUM(journal_voucher_lines.debit) - SUM(journal_voucher_lines.credit)) as movement_abs'),
            ])
            ->groupBy('accounts.id', 'accounts.name', 'accounts.code', 'accounts.nature');

        if ($natureNeedles) {
            $query->where(function ($q) use ($natureNeedles) {
                foreach ($natureNeedles as $needle) {
                    $q->orWhere('accounts.nature', 'like', '%' . $needle . '%')
                        ->orWhere('accounts.name', 'like', '%' . $needle . '%');
                }
            });
        }

        if ($thisMonth) {
            $query->whereBetween('journal_vouchers.voucher_date', [now()->startOfMonth()->toDateString(), now()->endOfMonth()->toDateString()]);
        } else {
            $this->applyFiscalYear($query, $request, 'journal_vouchers', 'voucher_date');
        }

        $this->applyApprovedFinancialTruth($query, 'journal_vouchers');
        $this->applyBranch($query, $request, 'journal_vouchers');

        $records = $query->orderByDesc($sortColumn)->limit(10)->get()->map(fn ($row) => [
            'account_id' => (string) $row->id,
            'account_name' => $row->name,
            'account_code' => $row->code,
            'nature' => $row->nature,
            'debit_total' => $this->number($row->debit_total),
            'credit_total' => $this->number($row->credit_total),
            'movement' => $this->number($row->movement_abs),
            'open_url' => '/accounting/accounts/' . $row->id,
        ])->all();

        return AiToolResult::query($tool, $title, $records, array_merge($this->contextFilters($request), ['approved' => true, 'void' => false]), count($records) ? $records[0]['account_name'] . ' is the top account for this query.' : 'No approved journal voucher movement was found.', '/accounting/accounts')->toArray();
    }
}
