<?php

namespace App\Services\AI\Tools;

use App\Models\AiConversation;
use App\Models\AiPendingAction;
use App\Services\AI\AiUsageLogger;
use App\Services\AI\AiSettingsService;
use App\Services\AI\Tools\Actions\CreateCashTransferDraftAction;
use App\Services\AI\Tools\Actions\CreateContactDraftAction;
use App\Services\AI\Tools\Actions\CreateCustomerPaymentDraftAction;
use App\Services\AI\Tools\Actions\CreateExpenseDraftAction;
use App\Services\AI\Tools\Actions\CreateInvoiceDraftAction;
use App\Services\AI\Tools\Actions\CreateJournalVoucherDraftAction;
use App\Services\AI\Tools\Actions\CreateProductDraftAction;
use App\Services\AI\Tools\Actions\CreatePurchaseBillDraftAction;
use App\Services\AI\Tools\Actions\CreatePurchaseOrderDraftAction;
use App\Services\AI\Tools\Actions\CreateQuotationDraftAction;
use App\Services\AI\Tools\Actions\CreateSalesOrderDraftAction;
use App\Services\AI\Tools\Actions\CreateSupplierPaymentDraftAction;
use App\Services\AI\Tools\Actions\UpdateInvoiceDraftAction;
use App\Services\AI\Tools\Queries\BankAccountQueryTool;
use App\Services\AI\Tools\Queries\ContactQueryTool;
use App\Services\AI\Tools\Queries\InventoryQueryTool;
use App\Services\AI\Tools\Queries\JournalVoucherQueryTool;
use App\Services\AI\Tools\Queries\PayableQueryTool;
use App\Services\AI\Tools\Queries\ProductQueryTool;
use App\Services\AI\Tools\Queries\PurchaseQueryTool;
use App\Services\AI\Tools\Queries\ReceivableQueryTool;
use App\Services\AI\Tools\Queries\ReportQueryTool;
use App\Services\AI\Tools\Queries\SalesQueryTool;
use Illuminate\Http\Request;
use Illuminate\Validation\ValidationException;

class AiToolRouter
{
    private array $queryTools = [
        'product.most_expensive' => [ProductQueryTool::class, 'mostExpensive', 'products'],
        'product.cheapest' => [ProductQueryTool::class, 'cheapest', 'products'],
        'product.highest_purchase_price' => [ProductQueryTool::class, 'highestPurchasePrice', 'products'],
        'product.highest_selling_price' => [ProductQueryTool::class, 'highestSellingPrice', 'products'],
        'product.low_stock' => [ProductQueryTool::class, 'lowStock', 'products'],
        'product.negative_stock' => [ProductQueryTool::class, 'negativeStock', 'products'],
        'product.without_price' => [ProductQueryTool::class, 'productsWithoutPrice', 'products'],
        'product.without_cost' => [ProductQueryTool::class, 'productsWithoutCost', 'products'],
        'bank_account.most_transactions' => [BankAccountQueryTool::class, 'mostTransactions', 'bank_accounts'],
        'bank_account.highest_debit_movement' => [BankAccountQueryTool::class, 'highestDebitMovement', 'bank_accounts'],
        'bank_account.highest_credit_movement' => [BankAccountQueryTool::class, 'highestCreditMovement', 'bank_accounts'],
        'bank_account.highest_net_movement' => [BankAccountQueryTool::class, 'highestNetMovement', 'bank_accounts'],
        'bank_account.balance_summary' => [BankAccountQueryTool::class, 'balanceSummary', 'bank_accounts'],
        'bank_account.recent_transactions' => [BankAccountQueryTool::class, 'recentTransactions', 'bank_accounts'],
        'journal_voucher.cash_balance' => [JournalVoucherQueryTool::class, 'cashBalance', 'journal_vouchers'],
        'journal_voucher.bank_balance' => [JournalVoucherQueryTool::class, 'bankBalance', 'journal_vouchers'],
        'journal_voucher.highest_debit_movement' => [JournalVoucherQueryTool::class, 'highestDebitMovement', 'journal_vouchers'],
        'journal_voucher.highest_credit_movement' => [JournalVoucherQueryTool::class, 'highestCreditMovement', 'journal_vouchers'],
        'journal_voucher.highest_expense_this_month' => [JournalVoucherQueryTool::class, 'highestExpenseThisMonth', 'journal_vouchers'],
        'journal_voucher.highest_income_this_month' => [JournalVoucherQueryTool::class, 'highestIncomeThisMonth', 'journal_vouchers'],
        'journal_voucher.source' => [JournalVoucherQueryTool::class, 'sourceForVoucher', 'journal_vouchers'],
        'journal_voucher.auto_generated_this_month' => [JournalVoucherQueryTool::class, 'autoGeneratedThisMonth', 'journal_vouchers'],
        'journal_voucher.unbalanced' => [JournalVoucherQueryTool::class, 'unbalanced', 'journal_vouchers'],
        'journal_voucher.source_modules_most_jvs' => [JournalVoucherQueryTool::class, 'sourceModulesMostJvs', 'journal_vouchers'],
        'journal_voucher.abnormal_movement' => [JournalVoucherQueryTool::class, 'abnormalMovement', 'journal_vouchers'],
        'receivable.highest_customer_balance' => [ReceivableQueryTool::class, 'highestCustomerBalance', 'receivable'],
        'receivable.total' => [ReceivableQueryTool::class, 'totalReceivable', 'receivable'],
        'receivable.overdue' => [ReceivableQueryTool::class, 'overdueReceivable', 'receivable'],
        'receivable.top_overdue_customers' => [ReceivableQueryTool::class, 'topOverdueCustomers', 'receivable'],
        'receivable.unpaid_invoices' => [ReceivableQueryTool::class, 'unpaidInvoices', 'receivable'],
        'receivable.partially_paid_invoices' => [ReceivableQueryTool::class, 'partiallyPaidInvoices', 'receivable'],
        'receivable.customer_ageing' => [ReceivableQueryTool::class, 'customerAgeing', 'receivable'],
        'payable.highest_supplier_balance' => [PayableQueryTool::class, 'highestSupplierBalance', 'payable'],
        'payable.total' => [PayableQueryTool::class, 'totalPayable', 'payable'],
        'payable.overdue' => [PayableQueryTool::class, 'overduePayable', 'payable'],
        'payable.top_overdue_suppliers' => [PayableQueryTool::class, 'topOverdueSuppliers', 'payable'],
        'payable.unpaid_bills' => [PayableQueryTool::class, 'unpaidBills', 'payable'],
        'payable.partially_paid_bills' => [PayableQueryTool::class, 'partiallyPaidBills', 'payable'],
        'payable.supplier_ageing' => [PayableQueryTool::class, 'supplierAgeing', 'payable'],
        'sales.today' => [SalesQueryTool::class, 'salesToday', 'invoices'],
        'sales.this_month' => [SalesQueryTool::class, 'salesThisMonth', 'invoices'],
        'sales.top_customer' => [SalesQueryTool::class, 'topCustomerBySales', 'invoices'],
        'sales.top_invoice' => [SalesQueryTool::class, 'topInvoiceByAmount', 'invoices'],
        'sales.unpaid_invoices' => [SalesQueryTool::class, 'unpaidInvoices', 'invoices'],
        'sales.draft_invoices' => [SalesQueryTool::class, 'draftInvoices', 'invoices'],
        'sales.approved_invoices' => [SalesQueryTool::class, 'approvedInvoices', 'invoices'],
        'sales.by_branch' => [SalesQueryTool::class, 'salesByBranch', 'invoices'],
        'sales.by_product' => [SalesQueryTool::class, 'salesByProduct', 'invoices'],
        'sales.by_status' => [SalesQueryTool::class, 'salesByStatus', 'invoices'],
        'purchase.today' => [PurchaseQueryTool::class, 'purchasesToday', 'purchase_bills'],
        'purchase.this_month' => [PurchaseQueryTool::class, 'purchasesThisMonth', 'purchase_bills'],
        'purchase.top_supplier' => [PurchaseQueryTool::class, 'topSupplierByPurchase', 'purchase_bills'],
        'purchase.top_bill' => [PurchaseQueryTool::class, 'topBillByAmount', 'purchase_bills'],
        'purchase.unpaid_bills' => [PurchaseQueryTool::class, 'unpaidBills', 'purchase_bills'],
        'purchase.draft_bills' => [PurchaseQueryTool::class, 'draftPurchaseBills', 'purchase_bills'],
        'purchase.approved_bills' => [PurchaseQueryTool::class, 'approvedPurchaseBills', 'purchase_bills'],
        'purchase.by_branch' => [PurchaseQueryTool::class, 'purchaseByBranch', 'purchase_bills'],
        'purchase.by_product' => [PurchaseQueryTool::class, 'purchaseByProduct', 'purchase_bills'],
        'purchase.by_status' => [PurchaseQueryTool::class, 'purchaseByStatus', 'purchase_bills'],
        'inventory.low_stock' => [InventoryQueryTool::class, 'lowStock', 'inventory'],
        'inventory.negative_stock' => [InventoryQueryTool::class, 'negativeStock', 'inventory'],
        'inventory.value' => [InventoryQueryTool::class, 'inventoryValue', 'inventory'],
        'inventory.dead_stock' => [InventoryQueryTool::class, 'deadStock', 'inventory'],
        'inventory.fast_moving_products' => [InventoryQueryTool::class, 'fastMovingProducts', 'inventory'],
        'inventory.warehouse_wise_stock' => [InventoryQueryTool::class, 'warehouseWiseStock', 'inventory'],
        'inventory.products_without_cost' => [InventoryQueryTool::class, 'productsWithoutCost', 'inventory'],
        'inventory.stock_adjustment_risks' => [InventoryQueryTool::class, 'stockAdjustmentRisks', 'inventory'],
        'contact.search' => [ContactQueryTool::class, 'search', 'contacts'],
    ];

    private array $actionTools = [
        'action.create_invoice_draft' => [CreateInvoiceDraftAction::class, 'invoices'],
        'action.update_invoice_draft' => [UpdateInvoiceDraftAction::class, 'invoices'],
        'action.create_quotation_draft' => [CreateQuotationDraftAction::class, 'quotations'],
        'action.create_sales_order_draft' => [CreateSalesOrderDraftAction::class, 'sales_orders'],
        'action.create_customer_payment_draft' => [CreateCustomerPaymentDraftAction::class, 'customer_payments'],
        'action.create_purchase_order_draft' => [CreatePurchaseOrderDraftAction::class, 'purchase_orders'],
        'action.create_purchase_bill_draft' => [CreatePurchaseBillDraftAction::class, 'purchase_bills'],
        'action.create_supplier_payment_draft' => [CreateSupplierPaymentDraftAction::class, 'supplier_payments'],
        'action.create_expense_draft' => [CreateExpenseDraftAction::class, 'expenses'],
        'action.create_journal_voucher_draft' => [CreateJournalVoucherDraftAction::class, 'journal_vouchers'],
        'action.create_cash_transfer_draft' => [CreateCashTransferDraftAction::class, 'cash_transfers'],
        'action.create_product_draft' => [CreateProductDraftAction::class, 'products'],
        'action.create_contact_draft' => [CreateContactDraftAction::class, 'contacts'],
    ];

    public function __construct(private AiUsageLogger $usage, private AiSettingsService $settings)
    {
    }

    public function classify(string $message, array $payload = []): array
    {
        $m = mb_strtolower(trim($message));

        if ($this->containsAny($m, ['delete ', 'remove ', 'void ', 'approve ', 'post ', 'mark paid', 'closed fiscal year'])) {
            return $this->classification('action', 'action.blocked', 0.98, true, 'blocked', 'User requested a blocked write operation.');
        }

        if ($tool = $this->actionTool($m, $payload)) {
            if (! $this->settings->writeActionsEnabled()) {
                return $this->classification('action', 'action.blocked', 0.98, true, 'blocked', 'AI write actions are disabled in settings.');
            }
            return $this->classification('action', $tool, 0.88, true, $this->actionTools[$tool][1], 'User asked for a create/update action.');
        }

        if ($tool = $this->reportTool($m)) {
            return $this->classification('report', $tool, 0.86, false, 'reports', 'User asked to open or show a report.');
        }

        if ($tool = $this->queryTool($m)) {
            $module = $this->queryTools[$tool][2] ?? explode('.', $tool)[0];
            return $this->classification('query', $tool, 0.9, false, $module, 'User asked a factual business question that must use a database tool.');
        }

        if ($this->containsAny($m, ['explain', 'why', 'how does', 'what is this'])) {
            return $this->classification('explanation', 'assistant.explain', 0.58, false, $payload['module'] ?? 'general', 'User asked for explanation.');
        }

        return $this->classification('general_chat', 'assistant.chat', 0.5, false, 'general', 'No deterministic tool matched.');
    }

    public function runQuery(Request $request, array $classification): array
    {
        $tool = $classification['tool'];
        $config = $this->queryTools[$tool] ?? null;
        if (!$config) {
            throw ValidationException::withMessages(['tool' => 'Unsupported AI query tool.']);
        }

        $started = microtime(true);
        try {
            $result = app($config[0])->{$config[1]}($request);
            $this->usage->log([
                'user_id' => $request->user()?->id,
                'branch_id' => $result['filters']['branch_id'] ?? null,
                'module' => $tool,
                'status' => 'success',
                'duration_ms' => (int) round((microtime(true) - $started) * 1000),
            ]);
            return $result;
        } catch (\Throwable $e) {
            $this->usage->log([
                'user_id' => $request->user()?->id,
                'module' => $tool,
                'status' => 'error',
                'error_message' => $e->getMessage(),
                'duration_ms' => (int) round((microtime(true) - $started) * 1000),
            ]);
            throw $e;
        }
    }

    public function runReport(Request $request, array $classification, string $message): array
    {
        return app(ReportQueryTool::class)->resolve($request->merge(['message' => $message]), $message);
    }

    public function proposeAction(Request $request, AiConversation $conversation, array $classification, string $message, array $payload = []): AiPendingAction
    {
        $tool = $classification['tool'];
        if ($tool === 'action.blocked') {
            throw ValidationException::withMessages(['action' => 'AI cannot approve, void, delete, post, mark paid, or alter closed fiscal year data.']);
        }

        $config = $this->actionTools[$tool] ?? null;
        if (!$config) {
            throw ValidationException::withMessages(['tool' => 'Unsupported AI action tool.']);
        }

        return app($config[0])->propose($request, $conversation, $message, $payload);
    }

    public function explainToolResult(array $result): string
    {
        $summary = trim((string) ($result['summary'] ?? ''));
        if ($summary === '' && empty($result['records'])) {
            $summary = 'No data was found.';
        }
        if ($summary === '') {
            $summary = ($result['title'] ?? 'The tool') . ' returned ' . count($result['records'] ?? []) . ' record(s).';
        }

        if (!empty($result['filters'])) {
            $summary .= ' Filters: ' . collect($result['filters'])->map(fn ($v, $k) => $k . '=' . $v)->implode(', ') . '.';
        }

        if (!empty($result['open_url'])) {
            $summary .= ' Open: ' . $result['open_url'];
        }

        return $summary;
    }

    private function queryTool(string $m): ?string
    {
        if ($this->containsAny($m, ['which bank account has the most transactions', 'bank account has most transactions'])) return 'bank_account.most_transactions';
        if (str_contains($m, 'bank account') && str_contains($m, 'debit')) return 'bank_account.highest_debit_movement';
        if (str_contains($m, 'bank account') && str_contains($m, 'credit')) return 'bank_account.highest_credit_movement';
        if (str_contains($m, 'bank account') && str_contains($m, 'balance')) return 'bank_account.balance_summary';
        if (str_contains($m, 'recent') && str_contains($m, 'bank')) return 'bank_account.recent_transactions';
        if ($this->containsAny($m, ['cash balance', 'cash in hand'])) return 'journal_voucher.cash_balance';
        if ($this->containsAny($m, ['bank balance'])) return 'journal_voucher.bank_balance';
        if (str_contains($m, 'highest debit')) return 'journal_voucher.highest_debit_movement';
        if (str_contains($m, 'highest credit')) return 'journal_voucher.highest_credit_movement';
        if (str_contains($m, 'expense') && str_contains($m, 'highest')) return 'journal_voucher.highest_expense_this_month';
        if ($this->containsAny($m, ['income account', 'revenue account']) && str_contains($m, 'highest')) return 'journal_voucher.highest_income_this_month';
        if (str_contains($m, 'unbalanced') && $this->containsAny($m, ['jv', 'journal'])) return 'journal_voucher.unbalanced';
        if (str_contains($m, 'auto-generated') && $this->containsAny($m, ['jv', 'journal'])) return 'journal_voucher.auto_generated_this_month';
        if (str_contains($m, 'source module') && $this->containsAny($m, ['jv', 'journal'])) return 'journal_voucher.source_modules_most_jvs';
        if (str_contains($m, 'abnormal movement')) return 'journal_voucher.abnormal_movement';
        if ($this->containsAny($m, ['most expensive product', 'costliest product']) || (str_contains($m, 'product') && str_contains($m, 'most expensive'))) return 'product.most_expensive';
        if ($this->containsAny($m, ['cheapest product', 'lowest priced product', 'lowest price product'])) return 'product.cheapest';
        if (str_contains($m, 'highest purchase price')) return 'product.highest_purchase_price';
        if (str_contains($m, 'highest selling price')) return 'product.highest_selling_price';
        if (str_contains($m, 'product') && str_contains($m, 'without price')) return 'product.without_price';
        if (str_contains($m, 'product') && $this->containsAny($m, ['without cost', 'without purchase cost'])) return 'product.without_cost';
        if (str_contains($m, 'low stock')) return 'inventory.low_stock';
        if (str_contains($m, 'negative stock')) return 'inventory.negative_stock';
        if (str_contains($m, 'inventory value')) return 'inventory.value';
        if (str_contains($m, 'warehouse') && str_contains($m, 'stock')) return 'inventory.warehouse_wise_stock';
        if (str_contains($m, 'fast moving')) return 'inventory.fast_moving_products';
        if (str_contains($m, 'highest receivable') || str_contains($m, 'customer has highest receivable')) return 'receivable.highest_customer_balance';
        if (str_contains($m, 'total receivable')) return 'receivable.total';
        if (str_contains($m, 'overdue receivable')) return 'receivable.overdue';
        if (str_contains($m, 'unpaid invoice')) return str_contains($m, 'sales') ? 'sales.unpaid_invoices' : 'receivable.unpaid_invoices';
        if (str_contains($m, 'partially paid invoice')) return 'receivable.partially_paid_invoices';
        if (str_contains($m, 'highest payable') || str_contains($m, 'supplier has highest payable')) return 'payable.highest_supplier_balance';
        if (str_contains($m, 'total payable')) return 'payable.total';
        if (str_contains($m, 'overdue payable')) return 'payable.overdue';
        if (str_contains($m, 'unpaid bill')) return 'payable.unpaid_bills';
        if (str_contains($m, 'partially paid bill')) return 'payable.partially_paid_bills';
        if ($this->containsAny($m, ['sales today', "today's sales"])) return 'sales.today';
        if (str_contains($m, 'sales this month')) return 'sales.this_month';
        if (str_contains($m, 'top customer') && str_contains($m, 'sales')) return 'sales.top_customer';
        if (str_contains($m, 'top invoice')) return 'sales.top_invoice';
        if (str_contains($m, 'draft invoice')) return 'sales.draft_invoices';
        if (str_contains($m, 'approved invoice')) return 'sales.approved_invoices';
        if (str_contains($m, 'sales by product')) return 'sales.by_product';
        if (str_contains($m, 'sales by branch')) return 'sales.by_branch';
        if (str_contains($m, 'sales by status')) return 'sales.by_status';
        if ($this->containsAny($m, ['purchases today', "today's purchases", 'purchase today'])) return 'purchase.today';
        if (str_contains($m, 'purchase this month') || str_contains($m, 'purchases this month')) return 'purchase.this_month';
        if (str_contains($m, 'top supplier') && $this->containsAny($m, ['purchase', 'purchases'])) return 'purchase.top_supplier';
        if (str_contains($m, 'top bill')) return 'purchase.top_bill';
        if (str_contains($m, 'draft purchase bill')) return 'purchase.draft_bills';
        if (str_contains($m, 'approved purchase bill')) return 'purchase.approved_bills';
        if (str_contains($m, 'purchase by product')) return 'purchase.by_product';
        if (str_contains($m, 'purchase by branch')) return 'purchase.by_branch';
        if (str_contains($m, 'purchase by status')) return 'purchase.by_status';
        if ($this->containsAny($m, ['find customer', 'find supplier', 'search contact', 'show contact'])) return 'contact.search';

        return null;
    }

    private function reportTool(string $m): ?string
    {
        if (!$this->containsAny($m, ['report', 'trial balance', 'general ledger', 'income statement', 'profit and loss', 'balance sheet', 'cash flow', 'ageing', 'aging', 'vat summary', 'inventory position'])) {
            return null;
        }

        return 'report.resolve';
    }

    private function actionTool(string $m, array $payload): ?string
    {
        if ($this->containsAny($m, ['update ', 'change ', 'modify ', 'edit ', 'set '])) {
            if (str_contains($m, 'invoice') || (($payload['module'] ?? null) === 'invoices')) {
                return 'action.update_invoice_draft';
            }
        }

        if (!$this->containsAny($m, ['create ', 'make ', 'add ', 'prepare ', 'draft ', 'new '])) {
            return null;
        }

        return match (true) {
            str_contains($m, 'quotation') || str_contains($m, 'quote') => 'action.create_quotation_draft',
            str_contains($m, 'sales order') => 'action.create_sales_order_draft',
            str_contains($m, 'customer payment') || str_contains($m, 'receipt') => 'action.create_customer_payment_draft',
            str_contains($m, 'purchase order') => 'action.create_purchase_order_draft',
            str_contains($m, 'purchase bill') || str_contains($m, 'supplier bill') => 'action.create_purchase_bill_draft',
            str_contains($m, 'supplier payment') => 'action.create_supplier_payment_draft',
            str_contains($m, 'expense') => 'action.create_expense_draft',
            str_contains($m, 'journal voucher') || str_contains($m, 'journal entry') || str_contains($m, ' jv') => 'action.create_journal_voucher_draft',
            str_contains($m, 'cash transfer') => 'action.create_cash_transfer_draft',
            str_contains($m, 'product') || str_contains($m, 'item') => 'action.create_product_draft',
            str_contains($m, 'contact') || str_contains($m, 'customer') || str_contains($m, 'supplier') => 'action.create_contact_draft',
            str_contains($m, 'invoice') => 'action.create_invoice_draft',
            default => null,
        };
    }

    private function classification(string $type, string $tool, float $confidence, bool $approval, string $module, string $reason): array
    {
        return [
            'type' => $type,
            'tool' => $tool,
            'confidence' => $confidence,
            'requires_approval' => $approval,
            'module' => $module,
            'reason' => $reason,
        ];
    }

    private function containsAny(string $haystack, array $needles): bool
    {
        foreach ($needles as $needle) {
            if ($needle !== '' && str_contains($haystack, $needle)) {
                return true;
            }
        }

        return false;
    }
}
