import { Link } from '@inertiajs/react';
import { Alert, Button, Card, Col, Collapse, Dropdown, Row, Space, Typography } from 'antd';
import PublicSeo from './PublicSeo';

export default function Page({ page, plans = [], menus = {}, faqs = [], testimonials = [], site = {}, isPreview = false }) {
    return <>
        <PublicSeo record={page} site={site} isPreview={isPreview}/>
        {isPreview && <Alert banner type="warning" showIcon message={`Previewing ${page.status} content. This URL requires an authorized administrator.`}/>}
        <PublicHeader menus={menus} site={site}/>
        <main>
            {page?.body && <article style={{ maxWidth: page.layout === 'full_width' ? 'none' : 960, margin: '0 auto', padding: '64px 6vw' }}><Typography.Title>{page.title}</Typography.Title>{page.excerpt && <Typography.Paragraph style={{ fontSize: 18 }} type="secondary">{page.excerpt}</Typography.Paragraph>}<div dangerouslySetInnerHTML={{ __html: page.body }}/></article>}
            {page?.sections?.map((section) => <section key={section.id} style={{ padding: '72px 6vw', background: section.background_style || undefined, textAlign: section.alignment || 'left' }}>{section.eyebrow && <Typography.Text type="success" strong>{section.eyebrow}</Typography.Text>}<Typography.Title>{section.title}</Typography.Title>{section.subtitle && <Typography.Paragraph type="secondary" style={{ fontSize: 18 }}>{section.subtitle}</Typography.Paragraph>}{section.image && <img src={section.image} alt="" style={{ maxWidth: '100%', height: 'auto', marginBottom: 24 }}/>}<div dangerouslySetInnerHTML={{ __html: section.content || '' }}/>{section.items?.length > 0 && <Row gutter={[18, 18]}>{section.items.map((item, index) => <Col xs={24} md={8} key={index}><Card title={item.title}>{item.image && <img src={item.image} alt={item.alt || ''} style={{ width: '100%', height: 'auto' }}/>}<div dangerouslySetInnerHTML={{ __html: item.content || '' }}/></Card></Col>)}</Row>}<Space wrap style={{ marginTop: 18 }}>{section.button_text && <Button type="primary" href={section.button_url}>{section.button_text}</Button>}{section.secondary_button_text && <Button href={section.secondary_button_url}>{section.secondary_button_text}</Button>}</Space></section>)}
            {!!plans.length && <Row gutter={[24, 24]} style={{ padding: '64px 6vw' }}>{plans.map((plan) => <Col xs={24} md={8} key={plan.id}><Card title={plan.name}><Typography.Title>{plan.currency} {plan.price_monthly}<small>/mo</small></Typography.Title><p>{plan.description}</p><Button type={plan.is_featured ? 'primary' : 'default'}>Choose plan</Button></Card></Col>)}</Row>}
            {!!testimonials.length && <section style={{ padding: '64px 6vw' }}><Typography.Title>What teams value</Typography.Title><Row gutter={[18, 18]}>{testimonials.map((item) => <Col xs={24} md={8} key={item.id}><Card title={item.title}>{item.content}</Card></Col>)}</Row></section>}
            {!!faqs.length && <section style={{ padding: '64px 6vw' }}><Typography.Title>Frequently asked questions</Typography.Title><Collapse items={faqs.map((item) => ({ key: item.id, label: item.title, children: <p>{item.content}</p> }))}/></section>}
        </main>
        <PublicFooter menus={menus} site={site}/>
    </>;
}

function MenuLink({ item }) { const href = item.page ? `/${item.page.slug}` : item.url; const link = <a href={href} target={item.target === 'new_tab' ? '_blank' : undefined} rel={item.target === 'new_tab' ? 'noopener noreferrer' : undefined}>{item.label}</a>; return item.children?.length ? <Dropdown menu={{ items: item.children.map((child) => ({ key: child.id, label: <MenuLink item={child}/> })) }}>{link}</Dropdown> : link; }
export function PublicHeader({ menus = {}, site = {} }) { return <header style={{ padding: '18px 6vw', display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 20, borderBottom: '1px solid #e5e7eb' }}><Link href={route('central.home')}><Typography.Title level={3} style={{ margin: 0, color: site['branding.primary_color'] || '#0f766e' }}>{site['general.platform_name'] || 'KiteLedger'}</Typography.Title></Link><nav style={{ display: 'flex', gap: 18, alignItems: 'center' }}>{(menus.header || []).map((item) => <MenuLink key={item.id} item={item}/>)}<Link href={route('central.login')}><Button type="primary">Admin login</Button></Link></nav></header>; }
export function PublicFooter({ menus = {}, site = {} }) { return <footer style={{ padding: '36px 6vw', background: '#0f172a', color: '#cbd5e1', display: 'flex', justifyContent: 'space-between', gap: 20, flexWrap: 'wrap' }}><span>{site['branding.footer_text'] || 'KiteLedger'}</span><nav style={{ display: 'flex', gap: 16, flexWrap: 'wrap' }}>{[...(menus.footer || []), ...(menus.legal || []), ...(menus.product || []), ...(menus.resources || [])].map((item) => <span key={item.id} style={{ color: '#cbd5e1' }}><MenuLink item={item}/></span>)}</nav></footer>; }
