import CentralLayout from '@/Layouts/CentralLayout';
import PageHeader from '@/Components/Central/PageHeader';
import RichTextEditor from '@/Components/Central/RichTextEditor';
import SectionCard from '@/Components/Central/SectionCard';
import { ArrowDownOutlined, ArrowUpOutlined, DeleteOutlined, EditOutlined, PlusOutlined } from '@ant-design/icons';
import { router } from '@inertiajs/react';
import { Button, Drawer, Form, Input, InputNumber, Modal, Select, Space, Switch, Tag, Typography } from 'antd';
import { useState } from 'react';

export default function Sections({ pages, selectedPage, sections }) {
    const [record, setRecord] = useState(null);
    const [open, setOpen] = useState(false);
    const [form] = Form.useForm();
    const edit = (section = null) => { setRecord(section); form.resetFields(); form.setFieldsValue(section ? { ...section, items_json: JSON.stringify(section.items || [], null, 2), settings_json: JSON.stringify(section.settings || {}, null, 2) } : { page_id: selectedPage, section_type: 'content', alignment: 'left', is_active: true, sort_order: sections.length, items_json: '[]', settings_json: '{}' }); setOpen(true); };
    const save = (values) => {
        let items; let settings;
        try { items = JSON.parse(values.items_json || '[]'); settings = JSON.parse(values.settings_json || '{}'); } catch { form.setFields([{ name: 'items_json', errors: ['Items and settings must contain valid JSON.'] }]); return; }
        const payload = { ...values, items, settings }; delete payload.items_json; delete payload.settings_json;
        const options = { preserveScroll: true, onSuccess: () => setOpen(false) };
        record ? router.put(route('central.website-sections.update', record.id), payload, options) : router.post(route('central.website-sections.store'), payload, options);
    };
    const move = (index, direction) => { const ids = sections.map((section) => section.id); const target = index + direction; if (target < 0 || target >= ids.length) return; [ids[index], ids[target]] = [ids[target], ids[index]]; router.put(route('central.website-sections.reorder'), { page_id: selectedPage, ids }, { preserveScroll: true }); };
    const remove = (section) => Modal.confirm({ title: `Delete ${section.title || section.section_key}?`, content: 'The section will stop rendering on the public page.', okText: 'Delete section', okButtonProps: { danger: true }, onOk: () => router.delete(route('central.website-sections.destroy', section.id)) });
    return <CentralLayout title="Homepage Sections">
        <PageHeader eyebrow="Website" title="Section Builder" description="Compose page sections, repeatable items, calls to action, media, alignment, and reliable ordering." actions={<Button type="primary" icon={<PlusOutlined/>} onClick={() => edit()}>Add section</Button>}/>
        <SectionCard><div className="central-toolbar"><Select value={selectedPage} style={{ minWidth: 280 }} options={pages.map((page) => ({ value: page.id, label: page.title }))} onChange={(page_id) => router.get(route('central.website-sections.index'), { page_id })}/><span className="central-filter-summary">{sections.length} sections</span></div><Space direction="vertical" style={{ width: '100%' }} size={10}>{sections.map((section, index) => <div className="central-section-row" key={section.id}><span className="central-section-row__order"><Button icon={<ArrowUpOutlined/>} disabled={index === 0} aria-label="Move section up" onClick={() => move(index, -1)}/><Button icon={<ArrowDownOutlined/>} disabled={index === sections.length - 1} aria-label="Move section down" onClick={() => move(index, 1)}/></span><span className="central-section-row__copy"><Typography.Text strong>{section.title || section.section_key}</Typography.Text><span><Tag>{section.section_type}</Tag><Tag>{section.section_key}</Tag>{!section.is_active && <Tag color="warning">Hidden</Tag>}</span></span><Space><Button icon={<EditOutlined/>} onClick={() => edit(section)}>Edit</Button><Button danger icon={<DeleteOutlined/>} onClick={() => remove(section)}/></Space></div>)}</Space>{!sections.length && <div className="central-empty">No sections yet. Add the first section for this page.</div>}</SectionCard>
        <Drawer open={open} onClose={() => setOpen(false)} width={720} title={record ? 'Edit section' : 'Add section'} extra={<Button type="primary" onClick={() => form.submit()}>Save</Button>}><Form form={form} layout="vertical" onFinish={save}><Form.Item name="page_id" hidden><Input/></Form.Item><div className="central-two-column"><Form.Item name="section_key" label="Section key" rules={[{ required: true }]}><Input placeholder="hero"/></Form.Item><Form.Item name="section_type" label="Type" rules={[{ required: true }]}><Select options={['hero', 'logos', 'features', 'content', 'statistics', 'steps', 'pricing', 'testimonials', 'faq', 'cta', 'newsletter', 'footer'].map((value) => ({ value, label: value }))}/></Form.Item></div><div className="central-two-column"><Form.Item name="eyebrow" label="Eyebrow"><Input/></Form.Item><Form.Item name="title" label="Title"><Input/></Form.Item></div><Form.Item name="subtitle" label="Subtitle"><Input.TextArea rows={2}/></Form.Item><Form.Item name="content" label="Rich content"><RichTextEditor autosaveKey={`section.${record?.id || 'new'}`}/></Form.Item><div className="central-two-column"><Form.Item name="image" label="Image URL"><Input/></Form.Item><Form.Item name="video_url" label="Video URL"><Input type="url"/></Form.Item></div><div className="central-two-column"><Form.Item name="button_text" label="Primary button"><Input/></Form.Item><Form.Item name="button_url" label="Primary URL"><Input/></Form.Item></div><div className="central-two-column"><Form.Item name="secondary_button_text" label="Secondary button"><Input/></Form.Item><Form.Item name="secondary_button_url" label="Secondary URL"><Input/></Form.Item></div><div className="central-two-column"><Form.Item name="background_style" label="Background style"><Input placeholder="#f8fafc or theme token"/></Form.Item><Form.Item name="alignment" label="Alignment" rules={[{ required: true }]}><Select options={['left', 'center', 'right'].map((value) => ({ value, label: value }))}/></Form.Item></div><Form.Item name="items_json" label="Repeatable items (JSON)" rules={[{ validator: jsonValidator }]}><Input.TextArea rows={8} className="central-code"/></Form.Item><Form.Item name="settings_json" label="Section settings (JSON)" rules={[{ validator: jsonValidator }]}><Input.TextArea rows={5} className="central-code"/></Form.Item><Space size="large"><Form.Item name="sort_order" label="Sort order"><InputNumber min={0}/></Form.Item><Form.Item name="is_active" label="Active" valuePropName="checked"><Switch/></Form.Item></Space></Form></Drawer>
    </CentralLayout>;
}

const jsonValidator = (_, value) => { try { JSON.parse(value || '{}'); return Promise.resolve(); } catch { return Promise.reject(new Error('Enter valid JSON.')); } };
