import CentralLayout from '@/Layouts/CentralLayout';
import PageHeader from '@/Components/Central/PageHeader';
import SectionCard from '@/Components/Central/SectionCard';
import StatusBadge from '@/Components/Central/StatusBadge';
import { humanize } from '@/Components/Central/formatters';
import { DeleteOutlined, EditOutlined, PlusOutlined, SearchOutlined } from '@ant-design/icons';
import { router } from '@inertiajs/react';
import { Button, DatePicker, Drawer, Form, Input, InputNumber, Modal, Select, Space, Switch, Table } from 'antd';
import dayjs from 'dayjs';
import { useState } from 'react';

const definitions={
 features:{title:'Website Features',description:'Publish image-led feature stories independently from subscription controls.',columns:['title','slug','status','sort_order'],fields:['title','slug','excerpt','body','featured_media_id','status','sort_order','seo_title','meta_description','canonical_url','og_title','og_description','og_image','published_at']},
 'resource-categories':{title:'Resource Categories',description:'Organize mini-documentation into clear topics.',columns:['name','slug','status','sort_order'],fields:['name','slug','description','status','sort_order']},
 'resource-articles':{title:'Resource Articles',description:'Create searchable illustrated documentation.',columns:['title','category','status','published_at','sort_order'],fields:['category_id','title','slug','excerpt','body','featured_media_id','gallery_media_ids','status','sort_order','seo_title','meta_description','canonical_url','og_title','og_description','og_image','published_at']},
 'contact-locations':{title:'Contact Locations',description:'Manage offices, contact details, hours, and Google Maps embeds.',columns:['name','address','email','phone','is_active','sort_order'],fields:['name','address','email','phone','business_hours','map_embed_url','is_active','sort_order']},
 'social-links':{title:'Social Media',description:'Control social links displayed in the website footer.',columns:['platform','url','is_active','sort_order'],fields:['platform','url','icon','is_active','sort_order']},
 popups:{title:'Homepage Popups',description:'Schedule dismissible image and link promotions.',columns:['title','frequency','is_active','starts_at','ends_at'],fields:['title','content','media_id','cta_label','cta_url','target','frequency','is_dismissible','is_active','starts_at','ends_at']},
 'navbar-notifications':{title:'Navbar Notifications',description:'Publish scheduled notices above the public navigation.',columns:['content','link_label','is_active','starts_at','ends_at','sort_order'],fields:['content','link_label','link_url','target','is_dismissible','is_active','sort_order','starts_at','ends_at']},
};
export default function StructuredContent({resource,rows,filters={},categories=[],media=[]}){
 const def=definitions[resource];const [open,setOpen]=useState(false);const [record,setRecord]=useState(null);const [search,setSearch]=useState(filters.search||'');const [form]=Form.useForm();
 const edit=(row=null)=>{setRecord(row);form.resetFields();form.setFieldsValue({...row,starts_at:row?.starts_at?dayjs(row.starts_at):null,ends_at:row?.ends_at?dayjs(row.ends_at):null,published_at:row?.published_at?dayjs(row.published_at):null});setOpen(true)};
 const save=values=>{for(const key of ['starts_at','ends_at','published_at'])if(values[key])values[key]=values[key].toISOString();const opts={preserveScroll:true,onSuccess:()=>setOpen(false)};record?router.patch(route('central.website-structured.update',[resource,record.id]),values,opts):router.post(route('central.website-structured.store',resource),values,opts)};
 const remove=row=>Modal.confirm({title:`Remove ${row.title||row.name||row.platform||'content'}?`,okButtonProps:{danger:true},onOk:()=>router.delete(route('central.website-structured.destroy',[resource,row.id]))});
 const input=field=>{if(['is_active','is_dismissible'].includes(field))return <Switch/>;if(['sort_order'].includes(field))return <InputNumber min={0} style={{width:'100%'}}/>;if(['starts_at','ends_at','published_at'].includes(field))return <DatePicker showTime style={{width:'100%'}}/>;if(['featured_media_id','media_id'].includes(field))return <Select allowClear showSearch optionFilterProp="label" options={media.map(m=>({value:m.id,label:m.title||m.original_filename}))}/>;if(field==='gallery_media_ids')return <Select mode="multiple" options={media.map(m=>({value:m.id,label:m.title||m.original_filename}))}/>;if(field==='category_id')return <Select allowClear options={categories.map(c=>({value:c.id,label:c.name}))}/>;if(field==='status')return <Select options={['draft','published','archived','active','inactive'].map(value=>({value,label:humanize(value)}))}/>;if(field==='target')return <Select options={[{value:'same_tab',label:'Same tab'},{value:'new_tab',label:'New tab'}]}/>;if(field==='frequency')return <Select options={['always','session','once'].map(value=>({value,label:humanize(value)}))}/>;if(['body','content','excerpt','description','address','business_hours','meta_description','og_description'].includes(field))return <Input.TextArea rows={field==='body'?8:3}/>;return <Input/>};
 const columns=def.columns.map(key=>({title:humanize(key),key,render:(_,row)=>key==='category'?row.category?.name||'Uncategorized':key==='status'?<StatusBadge value={row.status}/>:key==='is_active'?<StatusBadge value={row.is_active?'active':'inactive'}/>:String(row[key]??'—')}));columns.push({title:'',width:110,render:(_,row)=><Space><Button icon={<EditOutlined/>} onClick={()=>edit(row)}/><Button danger icon={<DeleteOutlined/>} onClick={()=>remove(row)}/></Space>});
 return <CentralLayout title={def.title}><PageHeader eyebrow="Website" title={def.title} description={def.description} actions={<Button type="primary" icon={<PlusOutlined/>} onClick={()=>edit()}>Add new</Button>}/><SectionCard><div className="central-toolbar"><Input.Search value={search} onChange={e=>setSearch(e.target.value)} onSearch={()=>router.get(window.location.pathname,{search:search||undefined})} prefix={<SearchOutlined/>} allowClear/><span>{rows.total} records</span></div><Table rowKey="id" dataSource={rows.data} columns={columns} scroll={{x:850}} pagination={{current:rows.current_page,total:rows.total,pageSize:rows.per_page,onChange:page=>router.get(window.location.pathname,{...filters,page})}}/></SectionCard><Drawer open={open} onClose={()=>setOpen(false)} width={680} title={record?'Edit content':'Add content'} extra={<Button type="primary" onClick={()=>form.submit()}>Save</Button>}><Form form={form} layout="vertical" onFinish={save} initialValues={{status:resource==='resource-categories'?'active':'draft',is_active:true,is_dismissible:true,sort_order:0,target:'same_tab',frequency:'once'}}>{def.fields.map(field=><Form.Item key={field} name={field} label={humanize(field)} valuePropName={['is_active','is_dismissible'].includes(field)?'checked':'value'} rules={['title','name','platform','url','address','content','body','slug'].includes(field)?[{required:true}]:[]}>{input(field)}</Form.Item>)}</Form></Drawer></CentralLayout>;
}
