import CentralLayout from '@/Layouts/CentralLayout';
import PageHeader from '@/Components/Central/PageHeader';
import SectionCard from '@/Components/Central/SectionCard';
import { formatDate, humanize, initials } from '@/Components/Central/formatters';
import { useForm } from '@inertiajs/react';
import { Alert, Avatar, Button, Col, Form, Input, Row, Select, Space, Typography } from 'antd';

export default function Edit({ admin, activity = [], mfa = {} }) {
    const profile = useForm({ name: admin.name || '', email: admin.email || '', locale: admin.locale || 'en', timezone: admin.timezone || 'UTC', avatar: null });
    const password = useForm({ current_password: '', password: '', password_confirmation: '' });
    const mfaSetup = useForm({ current_password: '' });
    const mfaConfirm = useForm({ code: '' });
    const mfaDisable = useForm({ current_password: '', code: '' });
    const save = () => profile.post(route('central.profile.update'), { forceFormData: true, _method: 'patch' });

    return <CentralLayout title="My Profile"><PageHeader eyebrow="Account" title="My Profile" description="Manage your identity, security, working preferences, and password."/><Row gutter={[16,16]}><Col xs={24} lg={15}>
        <SectionCard title="Personal information"><Space align="center" size="large" style={{marginBottom:20}}><Avatar size={76} src={admin.avatar_path ? `/storage/${admin.avatar_path}` : undefined}>{initials(admin.name)}</Avatar><input type="file" accept="image/png,image/jpeg,image/webp" onChange={event => profile.setData('avatar', event.target.files[0])}/></Space><Form layout="vertical" onFinish={save}><Row gutter={14}><Col span={12}><Form.Item label="Name" validateStatus={profile.errors.name ? 'error' : ''} help={profile.errors.name}><Input value={profile.data.name} onChange={event => profile.setData('name', event.target.value)}/></Form.Item></Col><Col span={12}><Form.Item label="Email"><Input value={profile.data.email} onChange={event => profile.setData('email', event.target.value)}/></Form.Item></Col><Col span={12}><Form.Item label="Locale"><Select value={profile.data.locale} onChange={value => profile.setData('locale', value)} options={['en','de','es','fr','pt','ar'].map(value => ({value,label:value.toUpperCase()}))}/></Form.Item></Col><Col span={12}><Form.Item label="Timezone"><Input value={profile.data.timezone} onChange={event => profile.setData('timezone', event.target.value)}/></Form.Item></Col></Row><Button type="primary" htmlType="submit" loading={profile.processing}>Save profile</Button></Form></SectionCard>
        <SectionCard title="Change password"><Form layout="vertical" onFinish={() => password.put(route('central.profile.password'), {onSuccess:() => password.reset()})}><Form.Item label="Current password" validateStatus={password.errors.current_password ? 'error' : ''} help={password.errors.current_password}><Input.Password value={password.data.current_password} onChange={event => password.setData('current_password', event.target.value)}/></Form.Item><Row gutter={14}><Col span={12}><Form.Item label="New password"><Input.Password value={password.data.password} onChange={event => password.setData('password', event.target.value)}/></Form.Item></Col><Col span={12}><Form.Item label="Confirm password"><Input.Password value={password.data.password_confirmation} onChange={event => password.setData('password_confirmation', event.target.value)}/></Form.Item></Col></Row><Button htmlType="submit" loading={password.processing}>Change password</Button></Form></SectionCard>
        <SectionCard title="Multi-factor authentication" description="Protect Super Admin access with a time-based authenticator code.">{mfa.enabled ? <><Alert type="success" showIcon message="Multi-factor authentication is enabled." style={{marginBottom:16}}/>{mfa.recovery_codes?.length > 0 && <Alert type="warning" showIcon message="Store these recovery codes now" description={<code style={{whiteSpace:'pre-wrap'}}>{mfa.recovery_codes.join('\n')}</code>} style={{marginBottom:16}}/>}<Form layout="vertical" onFinish={() => mfaDisable.delete(route('central.profile.mfa.disable'))}><Form.Item label="Current password" validateStatus={mfaDisable.errors.current_password ? 'error' : ''} help={mfaDisable.errors.current_password}><Input.Password value={mfaDisable.data.current_password} onChange={event => mfaDisable.setData('current_password', event.target.value)}/></Form.Item><Form.Item label="Authenticator or recovery code" validateStatus={mfaDisable.errors.code ? 'error' : ''} help={mfaDisable.errors.code}><Input value={mfaDisable.data.code} onChange={event => mfaDisable.setData('code', event.target.value)}/></Form.Item><Button danger htmlType="submit" loading={mfaDisable.processing}>Disable MFA</Button></Form></> : mfa.pending ? <><Alert type="info" showIcon message="Add this setup key to your authenticator app" description={<><Typography.Paragraph copyable={{text:mfa.secret}}><code>{mfa.secret}</code></Typography.Paragraph><Typography.Text type="secondary">The authenticator URI is also copyable below.</Typography.Text><Typography.Paragraph copyable={{text:mfa.uri}} ellipsis>{mfa.uri}</Typography.Paragraph></>} style={{marginBottom:16}}/><Form layout="vertical" onFinish={() => mfaConfirm.post(route('central.profile.mfa.confirm'))}><Form.Item label="Six-digit authenticator code" validateStatus={mfaConfirm.errors.code ? 'error' : ''} help={mfaConfirm.errors.code}><Input autoComplete="one-time-code" value={mfaConfirm.data.code} onChange={event => mfaConfirm.setData('code', event.target.value)}/></Form.Item><Button type="primary" htmlType="submit" loading={mfaConfirm.processing}>Confirm and enable MFA</Button></Form></> : <Form layout="vertical" onFinish={() => mfaSetup.post(route('central.profile.mfa.setup'))}><Typography.Paragraph type="secondary">Confirm your password to generate an authenticator setup key.</Typography.Paragraph><Form.Item label="Current password" validateStatus={mfaSetup.errors.current_password ? 'error' : ''} help={mfaSetup.errors.current_password}><Input.Password value={mfaSetup.data.current_password} onChange={event => mfaSetup.setData('current_password', event.target.value)}/></Form.Item><Button type="primary" htmlType="submit" loading={mfaSetup.processing}>Set up MFA</Button></Form>}</SectionCard>
    </Col><Col xs={24} lg={9}><SectionCard title="Account"><Typography.Paragraph><strong>Roles</strong><br/>{admin.roles?.map(role => role.label).join(', ') || humanize(admin.role)}</Typography.Paragraph><Typography.Paragraph><strong>Last login</strong><br/>{formatDate(admin.last_login_at,true)}</Typography.Paragraph></SectionCard><SectionCard title="Recent activity">{activity.map(item => <div className="central-health-row" key={item.id}><span>{humanize(item.action)}</span><Typography.Text type="secondary">{formatDate(item.created_at,true)}</Typography.Text></div>)}</SectionCard></Col></Row></CentralLayout>;
}
