import { Head, Link, router, usePage } from '@inertiajs/react';
import { AppstoreOutlined, BankOutlined, CreditCardOutlined, DashboardOutlined, FileTextOutlined, GlobalOutlined, LogoutOutlined, SettingOutlined, TeamOutlined } from '@ant-design/icons';
import { Button, Layout, Menu, Space, Typography } from 'antd';
const { Header, Sider, Content } = Layout;
const nav=[['central.dashboard','Dashboard',<DashboardOutlined/>],['central.tenants.index','Tenants',<TeamOutlined/>],['central.plans.index','Plans',<AppstoreOutlined/>],['central.subscriptions.index','Subscriptions',<CreditCardOutlined/>],['central.invoices.index','Invoices',<FileTextOutlined/>],['central.payments.index','Payments',<BankOutlined/>],['central.website-pages.index','Website CMS',<GlobalOutlined/>],['central.default-templates.index','Templates',<FileTextOutlined/>],['central.platform-settings.index','Settings',<SettingOutlined/>]];
export default function CentralLayout({title,children}){
 const page=usePage(); const items=nav.map(([routeName,label,icon])=>({key:route(routeName),label,icon,onClick:()=>router.visit(route(routeName))}));
 return <Layout style={{minHeight:'100vh'}}><Head title={title}/><Sider breakpoint="lg" collapsedWidth="0" theme="dark"><div style={{height:64,display:'grid',placeItems:'center',color:'white',fontWeight:800,fontSize:18}}>KiteLedger SaaS</div><Menu theme="dark" mode="inline" selectedKeys={[items.find(i=>page.url.startsWith(new URL(i.key,location.origin).pathname))?.key]} items={items}/></Sider><Layout><Header style={{background:'#fff',display:'flex',alignItems:'center',justifyContent:'space-between',padding:'0 24px',borderBottom:'1px solid #eee'}}><Typography.Title level={4} style={{margin:0}}>{title}</Typography.Title><Space><Link href={route('central.home')}>View website</Link><Button icon={<LogoutOutlined/>} onClick={()=>router.post(route('central.logout'))}>Logout</Button></Space></Header><Content style={{padding:24}}>{children}</Content></Layout></Layout>;
}
